-------------------------
-- Spanish Localization String resources
-- Huami Co, ltd. (2015)
-- Mejorado por PlatinumMI AKA MrPostman
-- 20150504
-------------------------
localization_es_rES_table = {
    calories_table={
		{str="≈ Pepino (100g)", calories=14},
		{str="≈ Caldo de pollo  (100g)", calories=15},
		{str="≈ Repollo (100g)", calories=16},
		{str="≈ Salsa de tomate (100g)", calories=19},
		{str="≈ Setas  (100g)", calories=20},
		{str="≈ Rábano (100g)", calories=21},
		{str="≈ Berenjena (100g)", calories=24},
		{str="≈ Calabaza (100g)", calories=25},
		{str="≈ Sopa de setas (100g)", calories=26},
		{str="≈ Brócoli (100g)", calories=27},
		{str="≈ Sopa de verduras (100g)", calories=28},
		{str="≈ Fresas (100g)", calories=30},
		{str="≈ Remolacha (100g)", calories=36},
		{str="≈ Manzana (100g)", calories=37},
		{str="≈ Naranja (100g)", calories=38},
		{str="≈ Sopa de patatas (100g)", calories=39},
		{str="≈ Sandía (100g)", calories=39},
		{str="≈ Vaso de leche desnatada (100g)", calories=40},
		{str="≈ Coca-Cola (100g)", calories=42},
		{str="≈ Red Bull (100g)", calories=45},
		{str="≈ Sopa de pescado (100g)", calories=46},
		{str="≈ Melocotón (100g)", calories=46},
		{str="≈ Queso(25g)", calories=48},
		{str="≈ Cerezas (100g)", calories=52},
		{str="≈ Zumo de naranja (100g)", calories=54},
		{str="≈ Leche semidesnatada (100g)", calories=58},
		{str="≈ Puré de patatas (100g)", calories=65},
		{str="≈ Sopa de guisantes (100g)", calories=66},
		{str="≈ Mango (100g)", calories=67},
		{str="≈ Lentejas (100g)", calories=68},
		{str="≈ Mermelada de fresa (100g)", calories=69},
		{str="≈ Yogourt (100g)", calories=70},
		{str="≈ Palitos de cangrejo (100g)", calories=73},
		{str="≈ Pulpo (100g)", calories=75},
		{str="≈ Copa de cava (100g)", calories=76},
		{str="≈ Vino (100g)", calories=78},
		{str="≈ Guiso de col 100g)", calories=81},
		{str="≈ Patatas cocidas (100g)", calories=82},
		{str="≈ Huevo hervido (55g)", calories=88},
		{str="≈ Plátano (100g)", calories=89},
		{str="≈ Judías verdes con tomate (100g)", calories=92},
		{str="≈ Ketchup (100g)", calories=93},
		{str="≈ Paella con verduras (100g)", calories=94},
		{str="≈ Pan integral tostado (1 rebanada)", calories=95},
		{str="≈ Atún (100g)", calories=96},
		{str="≈ Menestra de verduras (100g)", calories=99},
		{str="≈ Pescado blanco cocido (100g)", calories=102},
		{str="≈ Ensalada de frutas (100g)", calories=103},
		{str="≈ Filete de pavo (100g)", calories=104},
		{str="≈ Huevos revueltos", calories=119},
		{str="≈ Requesón (100g)", calories=136},
		{str="≈ Aguacate", calories=140},
		{str="≈ Café cappuccino (100g)", calories=140},
		{str="≈ Filete de ternera (100g)", calories=146},
		{str="≈ Estofado de carne (100g)", calories=148},
		{str="≈ Filete de pollo hHervido (100g)", calories=153},
		{str="≈ Patatas fritas (100g)", calories=154},
		{str="≈ Pizza margarita (100g)", calories=157},
		{str="≈ Albóndigas (100g)", calories=159},
		{str="≈ Pan de centeno (100g)", calories=165},
		{str="≈ Pavo asado ≈ (100g)", calories=165},
		{str="≈ Filete de pollo a la plancha (100g)", calories=184},
		{str="≈ Cerdo (100g)", calories=195},
		{str="≈ Salami (100g)", calories=198},
		{str="≈ Salmón (201g)", calories=201},
		{str="≈ Pasta boloñesa (100g)", calories=208},
		{str="≈ Pan negro (100g)", calories=214},
		{str="≈ Frutas confitadas (100g)", calories=216},
		{str="≈ Arenques (100g)", calories=217},
		{str="≈ Ensalada César (100g)", calories=221},
		{str="≈ Tortilla francesa (100g)", calories=222},
		{str="≈ Cerveza light (0,5l)", calories=225},
		{str="≈ Pan de avena (100g)", calories=226},
		{str="≈ Estofado de cordero (100g)", calories=226},
		{str="≈ Hamburguesa McDonalds", calories=229},
		{str="≈ Cerdo asado (100g)", calories=233},
		{str="≈ Pan blanco (100g)", calories=235},
		{str="≈ Pan de pita (100g)", calories=236},
		{str="≈ Vodka 40% (100g)", calories=237},
		{str="≈ Ravioli (100g)", calories=245},
		{str="≈ Caviar rojo ≈ (100g)", calories=249},
		{str="≈ Salchicha de pollo (100g)", calories=259},
		{str="≈ Albóndigas (100g)", calories=260},
		{str="≈ Pasas (100g)", calories=262},
		{str="≈ Cheeseburger McDonalds", calories=264},
		{str="≈ Bacalao ahumado (100g)", calories=270},
		{str="≈ McNuggets (100g)", calories=272},
		{str="≈ Salmón a la plancha (100g)", calories=283},
		{str="≈ Caviar negro (100g)", calories=289},
		{str="≈ Miel (100g)", calories=302},
		{str="≈ Patatas McDonalds (100g)", calories=303},
		{str="≈ Pastel de manzana ≈ (100g)", calories=306},
		{str="≈ Col rellena (100g)", calories=311},
		{str="≈ Pasteles (100g)", calories=322},
		{str="≈ Tortilla con queso (100g)", calories=324},
		{str="≈ Donuts (100g)", calories=329},
		{str="≈ Pastel de queso (100g)", calories=331},
		{str="≈ Döner Kebab (100g)", calories=339},
		{str="≈ Espaguetis (100g)", calories=344},
		{str="≈ Muffin (100g)", calories=345},
		{str="≈ Golosinas (100g)", calories=350},
		{str="≈ Copos de maíz (100g)",	calories=350},		
		{str="≈ Cereales (100g)", calories=363},
		{str="≈ Pasta al huevo (100g)",	calories=371},
		{str="≈ Mayonesa light (100g)",	calories=384},		
		{str="≈ Filete (100g)", calories=384},
		{str="≈ Crackers (100g)", calories=386},
		{str="≈ Azúcar (100g)", calories=398},
		{str="≈ Fabada (100g)",	calories=420},
		{str="≈ Churros (100g)",	calories=443},		
		{str="≈ Galletas de avena (100g)", calories=440},
		{str="≈ Lasaña (100g)", calories=460},
		{str="≈ Foie Gras (100g)", calories=462},
		{str="≈ Torta de miel (100g)", calories=478},
		{str="≈ Twix", calories=483},
		{str="≈ Snickers", calories=497},
		{str="≈ Tocino (100g)", calories=500},
		{str="≈ McDonalds BigMac", calories=510},
		{str="≈ Patatas fritas Lays (100g)", calories=510},
		{str="≈ KitKat", calories=524},
		{str="≈ Tiramisú (100g)", calories=540},
		{str="≈ Pringles (100g)", calories=540},
		{str="≈ Chocolate (100g)", calories=546},
		{str="≈ Salami (100g)", calories=568},
		{str="≈ Pavo asado (100g)", calories=620},
		{str="≈ Mayonesa (100g)",	calories=718},
		{str="≈ Mantequilla (100g)",	calories=752},		
		{str="≈ Aceite de oliva (100g)",	calories=900},
    },
    
    ok='Aceptar',

    hour='hrs',
    minute=' min',
    month='mes',
    day='día',
    step="pasos",
    km=' km',
    mile=' millas',
    minute_format='%d min',
    hour_minute_format='%dh %dm',
    hour_format='%d hrs',

    welcome_use="Bienvenido",
    last_week_walked_format='Has caminado %d pasos en la útima semana',
    last_week_walked_info_format='Has caminado %dkm | Consumidas %dkcal',
    last_month_walked_format='Has caminado %d pasos en el último mes',
    last_month_walked_info_format='Has caminado %dkm | Consumidas %dkcal',

    get_over_format=", unos %d gramos de grasa",
    click_to_get_help="Conoce más sobre Mi Band",
    take_a_walk="Da un paseo con tu Mi Band",
    take_a_walk_info="Mi Fit realizará un seguimiento de tus actividades a lo largo del día",
    unlock_hint="Desbloqueo automático",
    unlock_hint_info="Utiliza tu Mi Band para desbloquear el dispositivo de forma automática",
    unlock_password_hint="Establece una contraseña de bloqueo de pantalla para evitar el uso del dispositivo en caso de pérdida",
    unlock_password_hint_info="Las pulseras Mi Band proporcionan una satisfactoria experiencia en el desbloqueo de tu dispositivo",    
    no_data_hint_0="La Fundación Nacional del Sueño (US), recomienda dormir entre 7 y 9 horas por noche",
    no_data_hint_1="La perseverancia es la madre del éxito",
    no_data_hint_2="Lucha por progresar, no por conseguir la perfección",
    no_data_hint_3="No importa lo lento que vayas, ya lo haces mas rápido que cualquiera sentado en el sofá",
    not_binded_hint="No se ha añadido ningúna Mi Band a esta cuenta",
    not_binded_hint_info="También puedes hacer click en báscula en el menú",
    new_record_info="¡Acabas de batir un récord!",
    new_record_format="%d pasos, %s %d",
    today_goal_reached="¡Has alcanzado tu objetivo de hoy!",
    today_goal_reached_click_info="Haz click para ver el resumen del día",
    week_continue_reach_goal="Perfecto",
 
	challenge_format="¡Has alcanzado tu objetivo durante %d días seguidos!",
    personal_best_format="¡Tu racha más larga es de %d días!",
    continue_with_skips_title="Ayer no alcanzaste el objetivo. Parece que te tomaste el día de descanso",
    continue_with_skips_title_today="Hoy no alcanzaste tu objetivo. Parece que te tomaste el día de descanso",
    personal_best_with_skips_format=" Has conseguido %d días de descanso",
    continue_used_n_skips_format="¡Has alcanzado tu objetivo durante %d días seguidos! Has conseguido %d días de descanso",
    continue_used_0_skips_format="¡Has alcanzado tu objetivo durante %d días seguidos! Pero no te quedan días de descanso",
    personal_best_on_skip_day_title="¡%d días alcanzando tu objetivo! Te has ganado un día de descanso!",
    personal_best_on_skip_day_info="Si consigues tu objetivo durante 7 días seguidos ganas un día de descanso. Puedes utilizar días de descanso para cubrir días que no consigas llegar al bjetivo",
    manual_lazy_title="Hoy no alcanzaste tu objetivo",
    manual_lazy_subtitle="Tu racha continuará si marcas hoy como día de descanso",
    manual_lazy_title_used="Hoy es día de descanso",
    manual_lazy_subtitle_used="Puedes ganar más días de descanso batiendo récords personales",
    manual_fail_ytd_title = "Tu racha acabó ayer",
    manual_fail_ytd_subtitle = "La racha duró %d días",
    
		active_time_format_0="%d m",
    active_time_format_1="%d h",
    active_time_format_2="%d h %d m",
    activie_run_format_0="Has corrido %s. ¡Buen trabajo!",
    activie_run_format_1="Has corrido %s. ¡Lo estás haciendo fenomenal!",
    activie_run_format_2="Has corrido %s",
    activie_run_consumed="Has consumido %dkcal %s",

	get_distance_format="aproximadamente %d m",
    get_distance_format_british="%dpie",
    activity_walk_format="Entre las %s has caminado %d pasos %s",
    activity_walk_consumed_format="Consumidas %dkcal %s",
    activity_rope_skipping_format="%s has realizado %d saltos a la comba",
    activity_situp_format="%s has realizado %d abdominales",
    activity_consumed_format="Consumidas %dkcal %s",
    activity_activity_format="Actividad entre las %s. Total %s",
	activity_activity_format_run="Actividad entre las %s. Total %s. Corriste %s",
    last_night_sleeped_good_format="Anoche has dormido %s",
    last_night_sleeped_normal_format="Anoche has dormido %s",
    deep_sleep_format="En fase de sueño profundo %s",

    battery_low_info="Batería baja",
    battery_very_low_info="Batería muy baja. Carga tu Mi Band a la mayor brevedad posible",

    cannot_find_bracelet="No se detecta tu Mi Band",
    cannot_find_bracelet_info="Comprueba que la batería de tu Mi Band está cargada",
    
    bracelet_disconnect="¿Problemas para conectarte? Haz click para obtener ayuda",
    
    challenge_to_get="¡%s días desde que estableciste tu último récord!",
    record_reach_max="¡Has igualado tu récord!",
    new_record_born="¡Nuevo récord!",
	
	  ---====== Weather tips ===============
    weather_tips_title_0="Fuerte contaminación, trata de no salir",
    weather_tips_title_1="Fuerte contaminación, trata de no salir",
    weather_tips_info = "¡Hacer abdominales o saltar la comba son grandes ejericios de interior!",
        
        ---------------Weight scale -------------------
    welcome_use_weight_scale = "¡Hola!",
    welcome_use_weight_scale_info = "Conoce más sobre Mi báscula",
    welcome_use_weight_scale_not_bind = "Haz click para asociar la báscula",
    welcome_use_mi_health="¡Hola!",

    select_devices="Elije dispositivos a emparejar",
    daily_steps_not_comlete = "Te faltan %s pasos para completar el objetivo",
    
    am_format="%sAM",
    pm_format="%sPM",

}
