-------------------------
-- Traditional Chinese Localization String resources
-- Huami Co, ltd. (2014)
-- Herbert dai
-- 20140815
-------------------------
localization_zh_rTW_table = {
    calories_table={
        {str="≈1個茶葉蛋",	calories=96},
        {str="≈1片麵包",	calories=100},
        {str="≈1瓶冰紅茶",	calories=112},
        {str="≈1個煎蛋",	calories=118},
        {str="≈2串羊肉串",	calories=124},
        {str="≈1罐可樂",	calories=153},
        {str="≈3串羊肉串",	calories=186},
        {str="≈2個茶葉蛋",	calories=192},
        {str="≈2片麵包",	calories=200},
        {str="≈1碗米飯",	calories=210},
        {str="≈1個饅頭",	calories=221},
        {str="≈1根冰糖葫蘆",	calories=223},
        {str="≈2瓶冰紅茶",	calories=224},
        {str="≈1包小薯條",	calories=224},
        {str="≈1個蛋黄派",	calories=224},
        {str="≈2個煎蛋",	calories=236},
        {str="≈4串羊肉串",	calories=248},
        {str="≈1個漢堡",	calories=260},
        {str="≈1根油條",	calories=270},
        {str="≈1個肉包子",	calories=272},
        {str="≈3個茶葉蛋",	calories=288},
        {str="≈1個甜筒",	calories=290},
        {str="≈3片麵包",	calories=300},
        {str="≈2罐可樂",	calories=306},
        {str="≈1包中薯條",	calories=328},
        {str="≈3個煎蛋",	calories=354},
        {str="≈1個蛋塔",	calories=375},
        {str="≈4片麵包",	calories=400},
        {str="≈1包大薯條",	calories=402},
        {str="≈2碗米飯",	calories=420},
        {str="≈2個饅頭",	calories=442},
        {str="≈2根冰糖葫蘆",	calories=446},
        {str="≈1個蛋黄派",	calories=448},
        {str="≈1包速食麵",	calories=470},
        {str="≈5片麵包",	calories=500},
        {str="≈1盤蛋炒飯",	calories=516},
        {str="≈2個漢堡",	calories=520},
        {str="≈2根油條",	calories=540},
        {str="≈2個肉包子",	calories=544},
        {str="≈2個甜筒",	calories=580},
        {str="≈1碗速食麵",	calories=581},
        {str="≈1碗牛肉拉麵",	calories=593},
        {str="≈10串羊肉串",	calories=620},
        {str="≈3碗米飯",	calories=630},
        {str="≈3個饅頭",	calories=663},
        {str="≈2個蛋塔",	calories=750},
        {str="≈3根油條",	calories=810},
        {str="≈3個肉包子",	calories=816},
    },

    ok="確定",

    hour="小時",
    minute="分鐘",
    month="月",
    day="日",
    step="步",
    km="公里",
    mile="英里",
    minute_format="%d分鐘",
    hour_minute_format="%d小時%d分鐘",
    hour_format="%d小時",

    welcome_use="小米手環绑定成功",
    last_week_walked_format="上周共行走%d步",
    last_week_walked_info_format="共走了%s、消耗%d大卡",
    last_month_walked_format="上月共行走%d步",
    last_month_walked_info_format="共走了%s、消耗%d大卡",

    get_over_format=", 輕鬆甩掉%d克肥肉",
    click_to_get_help="點擊查看如何玩轉小米手環",
    take_a_walk="戴上小米手環走一走吧",
    take_a_walk_info="她會隨時記錄你的運動資訊, 做你的健康助手",
    unlock_hint="使用手環智慧解鎖手機螢幕",
    unlock_hint_info="告別傳統密碼解鎖時代",
    no_data_hint_0="運動的要義不在趣味而在繼續持久, 養成習慣",
    no_data_hint_1="慢跑可以幫助你快樂減壓, 讓你保持一份好心情。",
    no_data_hint_2="有氧訓練是減肥、強身的一個重要手段, 它包括健身操、跑步、踩自行車等。",
    no_data_hint_3="一個成年人的深度睡眠只占其整個睡眠時間的15%~20%, 也就平均90分鐘。",
    not_binded_hint="你還沒有綁定手環, 點擊綁定",
    not_binded_hint_info="也可以透過右上角菜單，點擊智能設備綁定",
    new_record_info="恭喜, 你創造自己的最高行走紀錄",
    new_record_format="新紀錄, %d步, %d月%d日",
    today_goal_reached="恭喜, 今天已達成目標",
    today_goal_reached_click_info="檢視今天的運動成績",
    week_continue_reach_goal="連續一周達成目標, 贊！",

    -- Continue reach goals string
    challenge_format="你已連續%d天達成目標",
    personal_best_format="個人歷史最高紀錄%d天",
    continue_with_skips_title="昨天未達標, 環環已經幫你使用假單過關啦！",
    continue_with_skips_title_today="今天未達標, 環環已經幫你使用假單過關啦！",
    personal_best_with_skips_format=", 剩餘%d張假單",
    continue_used_n_skips_format="連續達標%d天, 還有%d張假單可用",
    continue_used_0_skips_format="連續達標%d天, 假單已經用完了要加油囉～",
    personal_best_on_skip_day_title="恭喜獲得假單一張, 你已連續%d天達標",
    personal_best_on_skip_day_info="連續達標每滿7天即可獲得假單, 未達標時會自動使用",
    manual_lazy_title="今天還未達標哦, 是否要使用假單？",
    manual_lazy_subtitle="不想今天中斷連續達標, 就用假單吧",
    manual_lazy_title_used="今天已經使用假單, 好好放鬆一下吧",
    manual_lazy_subtitle_used="明天將會繼續累計連續達標",
    manual_fail_ytd_title = "很遺憾昨天未達標, 連續達標中斷",
    manual_fail_ytd_subtitle = "截至前天已連續%d天達標",

    active_time_format_0="%d分鐘",
    active_time_format_1="%d小時",
    active_time_format_2="%d小時%d分鐘",
    activie_run_format_0="跑了%s, 讚！",
    activie_run_format_1="狂奔了%s, 好樣的！",
    activie_run_format_2="跑了%s, 好耐力！",
    activie_run_consumed="消耗了%d大卡%s",

    get_distance_format="%d公尺",
    get_distance_format_british="%d英尺",
    activity_walk_format="%s走了%d步, 共%s",
    activity_walk_consumed_format="消耗了%d大卡%s",

    activity_rope_skipping_format="%s跳繩%d次",
    activity_situp_format="%s做了%d個仰臥起坐",
    activity_consumed_format="消耗了%d大卡%s",

    activity_activity_format="%s活動了%s, 共%s",
    activity_activity_format_run="%s活動了%s, 跑了%s",
    last_night_sleeped_good_format="昨晚睡了%s, 睡得不錯哦",
    last_night_sleeped_normal_format="昨晚睡了%s",
    deep_sleep_format="深睡%s",

    battery_low_info="手環電池電量低, 請及時充電",
    battery_very_low_info="手環電量過低即將關閉, 請充電",

    cannot_find_bracelet="無法尋找到手環？",
    cannot_find_bracelet_info="請確保手環有電且在手機旁邊",

    bracelet_disconnect = "無法連接手環？點擊查看詳細幫助",

    challenge_to_get="還有%s天即將創造新的紀錄 ",
    record_reach_max="恭喜你已經追平了自己的最高紀錄",
    new_record_born="新紀錄誕生",

    am_format="上午%s",
    pm_format="下午%s",

    --=================== Game =====================
    game_register="国庆七天日行万步, 赢取小米手机4",
    game_not_register_info="分享微博赢取微博大奖",
    game_register_info="已成功报名, 倒计时%s天",
    game_playing="国庆七天日行万步, 第%s天挑战中",
    game_playing_done="国庆七天日行万步, 第%s天达成",
    game_playing_lastday="最后一天即将完成日行万步挑战, 加油",
    game_playing_lastday_done="恭喜, 国庆七天日行万步挑战成功",
    game_playing_bonus_info="中将结果将在%s月%s日揭晓",
    click_to_show_result="点击查看活动进展",
    game_fail_title_ytd="很遗憾, 昨天未达成10000步",
    game_fail_title="很遗憾, %s月%s日未达成10000步",
    game_failed_title="国庆七天日行万步",
    game_fail_info="继续关注活动, 分享微博赢取微博大奖",

    game_bonus_hit="恭喜你成为“国庆七天日行万步”获奖者",
    game_bonus_hit_info="点击查看中奖结果",
    game_bonus_miss="国庆七天日行万步, 中奖结果已经揭晓",
    game_bonus_miss_info="快去看看哪些人中奖了吧",
    game_bonus_open="中奖结果将在%s月%s日揭晓, 敬请关注",
    game_bonus_open_tomorrow="中奖结果将在明天揭晓, 敬请关注",
    game_bonus_open_today="中奖结果将在今天揭晓, 敬请关注",

    share_to_content_for_event="“国庆七天日行万步得小米手机4”活动火热报名中，没有手环? 转发此微博即有机会赢取手环F码，点击链接查看活动详情。",
    game_share_to_registered="我报名参加了“日行万步得小米手机4”的活动，你愿意站在一旁默默祝福我还是一起来参加呢？离活动开始只剩%s天了, 快来报名吧",
    game_share_to_finished="今天10000步目标顺利完成",
    game_share_to_not_finished="向着10000步前进",
    game_share_to_failed="没想到呀，我居然挑战失败了",
    game_share_to_success="挑战成功！一共走了%s步",
    game_share_to_hit_bonus="一个不小心中奖了，快来围观给我点赞吧",
    game_share_to_not_hit_bonus="没有抽中，就当是给下次中奖攒人品了",
    less_than_one="不到1",

    ---====== Weather tips ===============
    weather_tips_title_0 = "空氣重度污染, 請儘量減少室外活動",
    weather_tips_title_1 = "空氣嚴重污染, 請儘量減少室外活動",
    weather_tips_info = "仰臥起坐、跳繩、平板支撐都是很棒的室內活動哦",

    ---------------Weight scale -------------------

    welcome_use_weight_scale = "小米智慧體重機綁定成功",
    welcome_use_weight_scale_info = "點選查看如何玩轉體重機",
    welcome_use_weight_scale_not_bind = "点击綁定小米智能秤",

    welcome_use_mi_health="歡迎使用小米運動",

    select_devices="還沒有綁定設備哦, 點選綁定吧",
    daily_steps_not_comlete = "今天還差%s步就達成目標啦！",
}
