-------------------------
-- Simplified Chinese Localization String resources
-- Huami Co, ltd. (2014)
-- Herbert dai
-- 20140731
-------------------------
localization_zh_rCN_table = {
    calories_table={
        {str="≈1个茶叶蛋",	calories=96},
        {str="≈1片面包",	calories=100},
        {str="≈1瓶冰红茶",	calories=112},
        {str="≈1个煎蛋",	calories=118},
        {str="≈2串羊肉串",	calories=124},
        {str="≈1罐可乐",	calories=153},
        {str="≈3串羊肉串",	calories=186},
        {str="≈2个茶叶蛋",	calories=192},
        {str="≈2片面包",	calories=200},
        {str="≈1碗米饭",	calories=210},
        {str="≈1个馒头",	calories=221},
        {str="≈1根冰糖葫芦",	calories=223},
        {str="≈2瓶冰红茶",	calories=224},
        {str="≈1包小薯条",	calories=224},
        {str="≈1个蛋黄派",	calories=224},
        {str="≈2个煎蛋",	calories=236},
        {str="≈4串羊肉串",	calories=248},
        {str="≈1个汉堡",	calories=260},
        {str="≈1根油条",	calories=270},
        {str="≈1个肉包子",	calories=272},
        {str="≈3个茶叶蛋",	calories=288},
        {str="≈1个甜筒",	calories=290},
        {str="≈3片面包",	calories=300},
        {str="≈2罐可乐",	calories=306},
        {str="≈1包中薯条",	calories=328},
        {str="≈3个煎蛋",	calories=354},
        {str="≈1个蛋挞",	calories=375},
        {str="≈4片面包",	calories=400},
        {str="≈1包大薯条",	calories=402},
        {str="≈2碗米饭",	calories=420},
        {str="≈2个馒头",	calories=442},
        {str="≈2根冰糖葫芦",	calories=446},
        {str="≈1个蛋黄派",	calories=448},
        {str="≈1包方便面",	calories=470},
        {str="≈5片面包",	calories=500},
        {str="≈1盘蛋炒饭",	calories=516},
        {str="≈2个汉堡",	calories=520},
        {str="≈2根油条",	calories=540},
        {str="≈2个肉包子",	calories=544},
        {str="≈2个甜筒",	calories=580},
        {str="≈1碗方便面",	calories=581},
        {str="≈1碗牛肉拉面",	calories=593},
        {str="≈10串羊肉串",	calories=620},
        {str="≈3碗米饭",	calories=630},
        {str="≈3个馒头",	calories=663},
        {str="≈2个蛋挞",	calories=750},
        {str="≈3根油条",	calories=810},
        {str="≈3个肉包子",	calories=816},
    },

    ok="确定",

    hour="小时",
    minute="分钟",
    month="月",
    day="日",
    step="步",
    km="公里",
    mile="英里",
    minute_format="%d分钟",
    hour_minute_format="%d小时%d分钟",
    hour_format="%d小时",

    welcome_use="小米手环绑定成功",
    last_week_walked_format="上周共行走%d步",
    last_week_walked_info_format="共走了%s、消耗%d千卡",
    last_month_walked_format="上月共行走%d步",
    last_month_walked_info_format="共走了%s、消耗%d千卡",

    get_over_format=", 轻松甩掉%d克肥肉",
    click_to_get_help="点击查看如何玩转小米手环",
    take_a_walk="戴上小米手环走一走吧",
    take_a_walk_info="她会随时记录你的运动信息, 做你的健康助手",
    unlock_hint="使用手环智能解锁手机屏幕",
    unlock_hint_info="告别传统密码解锁时代",
    unlock_password_hint="设置锁屏密码避免手机隐私泄露",
    unlock_password_hint_info="小米手环提供最便捷的解锁体验",
    no_data_hint_0="运动的要义不在趣味而在继续持久, 养成习惯",
    no_data_hint_1="慢跑可以帮助你快乐减压, 让你保持一份好心情",
    no_data_hint_2="有氧训练是减肥、强身的一个重要手段, 它包括健身操、跑步、蹬自行车等",
    no_data_hint_3="一个成年人的深度睡眠只占其整个睡眠时间的15%~20%, 也就平均90分钟",
    not_binded_hint="你还没有绑定手环, 点击绑定",
    not_binded_hint_info="也可以通过右上角菜单，点击智能设备绑定",
    new_record_info="恭喜, 你创造自己的最高行走纪录",
    new_record_format="新纪录, %d步, %d月%d日",
    today_goal_reached="恭喜, 今天已达成目标",
    today_goal_reached_click_info="点击查看今天的运动成绩",
    week_continue_reach_goal="连续一周达成目标, 赞！",

    -- Continue reach goals string
    challenge_format="你已连续%d天达成目标",
    personal_best_format="个人历史最高纪录%d天",
    continue_with_skips_title="昨天未达标, 环环已经帮你使用假条过关啦！",
    continue_with_skips_title_today="今天未达标, 环环已经帮你使用假条过关啦！",
    personal_best_with_skips_format=", 剩余%d张假条",
    continue_used_n_skips_format="连续达标%d天, 还有%d张假条可用",
    continue_used_0_skips_format="连续达标%d天, 假条已经用完了要加油咯～",
    personal_best_on_skip_day_title="恭喜获得假条一张, 你已连续%d天达标",
    personal_best_on_skip_day_info="连续达标每满7天即可获得假条, 未达标时会自动使用",
    manual_lazy_title="今天还未达标哦, 是否要使用假条？",
    manual_lazy_subtitle="不想今天中断连续达标, 就用假条吧",
    manual_lazy_title_used="今天已经使用假条, 好好放松一下吧",
    manual_lazy_subtitle_used="明天将会继续累计连续达标",
    manual_fail_ytd_title = "很遗憾昨天未达标, 连续达标中断",
    manual_fail_ytd_subtitle = "截至前天已连续%d天达标",

    active_time_format_0="%d分钟",
    active_time_format_1="%d小时",
    active_time_format_2="%d小时%d分钟",
    activie_run_format_0="跑了%s, 赞！",
    activie_run_format_1="狂奔了%s, 好样的！",
    activie_run_format_2="跑了%s, 好耐力！",
    activie_run_consumed="消耗了%d千卡%s",

    get_distance_format="%d米",
    get_distance_format_british="%d英尺",
    activity_walk_format="%s走了%d步, 共%s",
    activity_walk_consumed_format="消耗了%d千卡%s",

    activity_rope_skipping_format="%s跳绳%d次",
    activity_situp_format="%s做了%d个仰卧起坐",
    activity_consumed_format="消耗了%d千卡%s",

    activity_activity_format="%s活动了%s, 共%s",
    activity_activity_format_run="%s活动了%s, 跑了%s",
    last_night_sleeped_good_format="昨晚睡了%s, 睡得不错哦",
    last_night_sleeped_normal_format="昨晚睡了%s",
    deep_sleep_format="深睡%s",

    battery_low_info="手环电池电量低, 请及时充电",
    battery_very_low_info="手环电量过低即将关闭, 请充电",

    cannot_find_bracelet="无法查找到手环？",
    cannot_find_bracelet_info="请确保手环有电且在手机旁边",

    bracelet_disconnect = "无法连接手环？点击查看详细帮助",

    challenge_to_get="还有%s天即将创造新的纪录",
    record_reach_max="恭喜你已经追平了自己的最高纪录",
    new_record_born="新纪录诞生",

    am_format="上午%s",
    pm_format="下午%s",

    ---=================== Game =====================
    game_register="国庆七天日行万步, 赢取小米手机4",
    game_not_register_info="分享微博赢取微博大奖",
    game_register_info="已成功报名, 倒计时%s天",
    game_playing="国庆七天日行万步, 第%s天挑战中",
    game_playing_done="国庆七天日行万步, 第%s天达成",
    game_playing_lastday="最后一天即将完成日行万步挑战, 加油",
    game_playing_lastday_done="恭喜, 国庆七天日行万步挑战成功",
    game_playing_bonus_info="中奖结果将在%s月%s日揭晓",
    click_to_show_result="点击查看活动进展",
    game_fail_title_ytd="很遗憾, 昨天未达成10000步",
    game_fail_title="很遗憾, %s月%s日未达成10000步",
    game_failed_title="国庆七天日行万步",
    game_fail_info="继续关注活动, 分享微博赢取微博大奖",

    game_bonus_hit="恭喜你成为“国庆七天日行万步”获奖者",
    game_bonus_hit_info="点击查看中奖结果",
    game_bonus_miss="国庆七天日行万步, 中奖结果已经揭晓",
    game_bonus_miss_info="快去看看哪些人中奖了吧",
    game_bonus_open="中奖结果将在%s月%s日揭晓, 敬请关注",
    game_bonus_open_tomorrow="中奖结果将在明天揭晓, 敬请关注",
    game_bonus_open_today="中奖结果将在今天揭晓, 敬请关注",


    share_to_content_for_event="“国庆七天日行万步得小米手机4”活动火热报名中，没有手环? 转发此微博即有机会赢取手环F码，点击链接查看活动详情。",
    game_share_to_registered="我报名参加了“日行万步得小米手机4”的活动，你愿意站在一旁默默祝福我还是一起来参加呢？离活动开始只剩%s天了, 快来报名吧",
    game_share_to_finished="今天10000步目标顺利完成",
    game_share_to_not_finished="向着10000步前进",
    game_share_to_failed="没想到呀，我居然挑战失败了",
    game_share_to_success="挑战成功！一共走了%s步",
    game_share_to_hit_bonus="一个不小心中奖了，快来围观给我点赞吧",
    game_share_to_not_hit_bonus="没有抽中，就当是给下次中奖攒人品了",
    less_than_one="小于1",

    ---====== Weather tips ===============
    weather_tips_title_0 = "空气重度污染, 请尽量减少室外活动",
    weather_tips_title_1 = "空气严重污染, 请尽量减少室外活动",
    weather_tips_info = "仰卧起坐、跳绳、平板支撑都是很棒的室内活动哦",

    ---------------Weight scale -------------------
    welcome_use_weight_scale = "小米体重秤绑定成功",
    welcome_use_weight_scale_info = "点击查看如何玩转体重秤",
    welcome_use_weight_scale_not_bind = "点击绑定小米体重秤",
    welcome_use_mi_health="欢迎使用小米运动",

    select_devices="还没有绑定设备哦, 点击绑定吧",
    daily_steps_not_comlete = "今天还差%s步就达成目标啦！",
}
