localization_indonisia_table = {
    calories_table={

    },

    ok='Oke',

    hour='jam',
    minute='mnt',
    month='bulan',
    day='hari',
    step="langkah",
    km='km',
    minute_format='%d mnt',
    hour_minute_format='%dj %dm',
    hour_format='%d jam',

    welcome_use="Selamat menggunakan",
    last_week_walked_format='Anda berjalan %d langkah minggu lalu.',
    last_week_walked_info_format='Berjalan %dkm, membakar %d kal.',
    last_month_walked_format='Anda berjalan %d langkah bulan lalu.',
    last_month_walked_info_format='Berjalan %dkm, membakar %d kal.',

    get_over_format=", sekitar %d gram lemak",
    click_to_get_help="Pelajari lebih lanjut tentang Mi Band",
    take_a_walk="Berjalan-jalan dengan band Anda",
    take_a_walk_info="Band Anda akan terus mencatat setiap langkah Anda sepanjang hari.",
    unlock_hint="Buka kunci perangkat dengan Mi Band",
    unlock_hint_info="Gunakan band untuk otomatis buka kunci perangkat Anda.",
    no_data_hint_0="Yayasan Tidur Nasional AS menyarankan waktu tidur 7-9 jam tiap malam.",
    no_data_hint_1="Pengulangan adalah kunci kesuksesan.",
    no_data_hint_2="Berjuang untuk kemajuan, bukan kesempurnaan.",
    no_data_hint_3="Tidak peduli seberapa lambat Anda berjalan, Anda masih mengalahkan orang yang duduk di sofa.",
    not_binded_hint="Tak ada band yang dipasangkan ke akun ini.",
    new_record_info="Anda telah membuat rekor baru!",
    new_record_format="%d langkah, %s %d",
    today_goal_reached="Anda mencapai target hari ini!",
    week_continue_reach_goal="Anda",

    challenge_format="Anda mencapai target %d hari berturut-turut!",
    personal_best_format="Capai target beruntun terpanjang %d hari!",
    continue_with_skips_title="Anda tidak mencapai target kemarin. Mari sebut sebagai Hari Malas ;)",
    continue_with_skips_title_today="Anda tidak mencapai target hari ini. Mari sebut sebagai Hari Malas ;)",
    personal_best_with_skips_format="Anda memiliki %d Hari Malas tersisa ;)",
    continue_used_n_skips_format="Anda mencapai target %d hari berturut-turut! Anda masih punya %d Hari Malas",
    continue_used_0_skips_format="Anda mencapai target %d hari berturut-turut! Hari Malas telah habis.",
    personal_best_on_skip_day_title="%d hari beruntun! Anda layak peroleh 1 Hari Malas!",
    personal_best_on_skip_day_info="Setelah 7 hari beruntun, Anda layak peroleh 1 Hari Malas. Anda bisa gunakan Hari Malas untuk ganti hari saat tidak capai target.",
    manual_lazy_title="Anda tidak mencapai target hari ini.",
    manual_lazy_subtitle="Capai target beruntun akan berlanjut jika Anda tandai hari ini sebagai Hari Malas.",
    manual_lazy_title_used="Hari ini adalah Hari Malas.",
    manual_lazy_subtitle_used="Anda dapat peroleh Hari Malas saat memecahkan rekor pribadi.",
    manual_fail_ytd_title = "Capai target beruntun berakhir kemarin.",
    manual_fail_ytd_subtitle = "Capai beruntun selama %d.",

    active_time_format_0="%dm",
    active_time_format_1="%dj",
    active_time_format_2="%dj %dm",
    activie_run_format_0="Lari %s. Bagus sekali!",
    activie_run_format_1="Lari %s. Hebat sekali!",
    activie_run_format_2="Lari %s.",
    activie_run_consumed="Membakar %d kal. %s",

    get_distance_format="sekitar %dm.",
    activity_walk_format="%s berjalan %d langkah, %s",
    activity_walk_consumed_format="Membakar %d cal %s.",
    activity_rope_skipping_format="%s lompat tali %d kali",
    activity_situp_format="%s %d sit up",
    activity_consumed_format="Membakar %d kal %s",
    activity_activity_format="%s olahraga selama %s, %s",
    activity_activity_format_run="%s olahraga selama %s, lari %s",
    last_night_sleeped_good_format="Anda tidur selama %s semalam.",
    last_night_sleeped_normal_format="Anda tidur selama %s semalam.",
    deep_sleep_format="Tidur lelap selama %s.",

    battery_low_info="Isi daya band Anda",
    battery_very_low_info="Baterai band Anda melemah.",

    cannot_find_bracelet="Tidak dapat menemukan band Anda.",
    cannot_find_bracelet_info="Pastikan baterai band telah diisi daya.",
    challenge_to_get="%s hari lagi dari membuat rekor baru!",
    record_reach_max="Anda menyamakan rekor Anda sebelumnya!",
    new_record_born="Anda membuat rekor baru.",

    weather_tips_title_0 = "Polusi berat, coba untuk tetap di dalam ruangan",
    weather_tips_title_0 = "Polusi berat, coba untuk tetap di dalam ruangan",
    weather_tips_info = "Sit up atau lompat tali adalah olahraga dalam ruangan yang baik",
}
