-------------------------
-- Translated and optimized by dezmen3
-- 4pda.ru
-- 20141103
-- Enjoy!
-------------------------
localization_Russian_table = {
    calories_table={
		{str="≈ Огурец грунт. (100г)",	calories=14},
		{str="≈ Бульон куриный (100г)",	calories=15},
		{str="≈ Капуста пекинская (100г)",	calories=16},
		{str="≈ Томаты соленые (100г)",	calories=19},
		{str="≈ Квас (100г)",	calories=20},
		{str="≈ Шампиньоны (100г)",	calories=20},
		{str="≈ Редис (100г)",	calories=21},
		{str="≈ Баклажаны (100г)",	calories=24},
		{str="≈ Тыква (100г)",	calories=25},
		{str="≈ Квашеная капуста (100г)",	calories=25},
		{str="≈ Айран (100г)",	calories=26},
		{str="≈ Грибной суп (100г)",	calories=26},
		{str="≈ Брокколи (100г)",	calories=27},
		{str="≈ Овощной суп (100г)",	calories=28},
		{str="≈ Клубника (100г)",	calories=30},
		{str="≈ Щи (100г)",	calories=31},
		{str="≈ Борщ (100г)",	calories=36},
		{str="≈ Суп мисо (100г)",	calories=36},
		{str="≈ Свекольник (100г)",	calories=36},
		{str="≈ Яблоко (100г)",	calories=37},
		{str="≈ Апельсин (100г)",	calories=38},
		{str="≈ Картофельный суп (100г)",	calories=39},
		{str="≈ Арбуз (100г)",	calories=39},
		{str="≈ Суп щавелевый (100г)",	calories=40},
		{str="≈ Простокваша 1% (100г)",	calories=40},
		{str="≈ Рассольник (100г)",	calories=42},
		{str="≈ Кока-Кола (100г)",	calories=42},
		{str="≈ Молоко 1.5% (100г)",	calories=45},
		{str="≈ Red Bull (100г)",	calories=45},
		{str="≈ Уха (100г)",	calories=46},
		{str="≈ Персик (100г)",	calories=46},
		{str="≈ Сыр Хохланд (25г)",	calories=48},
		{str="≈ Вишня (100г)",	calories=52},
		{str="≈ Апельсиновый сок (100г)",	calories=54},
		{str="≈ Кефир 3.2% (100г)",	calories=56},
		{str="≈ Окрошка (100г)",	calories=57},
		{str="≈ Молоко 3.2% (100г)",	calories=58},
		{str="≈ Аджика (100г)",	calories=59},
		{str="≈ Рататуй (100г)",	calories=60},
		{str="≈ Пюре с мол. (100г)",	calories=65},
		{str="≈ Гороховый суп (100г)",	calories=66},
		{str="≈ Манго (100г)",	calories=67},
		{str="≈ Овсяная каша (100г)",	calories=68},
		{str="≈ Суп из чечевицы (100г)",	calories=68},
		{str="≈ Клубничное желе (100г)",	calories=69},
		{str="≈ Солянка сборная (100г)",	calories=69},
		{str="≈ Йогурт 1.5% слад. (100г)",	calories=70},
		{str="≈ Крабовые палочки (100г)",	calories=73},
		{str="≈ Суп харчо (100г)",	calories=75},
		{str="≈ Кальмары (100г)",	calories=75},
		{str="≈ Шампанское (100г)",	calories=76},
		{str="≈ Вино 13% (100г)",	calories=78},
		{str="≈ Вареники с капустой (100г)",	calories=79},
		{str="≈ Гуляш с капустой (100г)",	calories=81},
		{str="≈ Картофель отварной (100г)",	calories=82},
		{str="≈ Абсент 60% (100г)",	calories=83},
		{str="≈ Пюре с мол.и масл. (100г)",	calories=85},
		{str="≈ Яйцо вареное (55г)",	calories=88},
		{str="≈ Банан (100г)",	calories=89},
		{str="≈ Кабачковая икра (100г)",	calories=90},
		{str="≈ Фасоль в томате (100г)",	calories=92},
		{str="≈ Кетчуп (100г)",	calories=93},
		{str="≈ Рис с овощами (100г)",	calories=94},
		{str="≈ Зерновой тост (1шт)",	calories=95},
		{str="≈ Тунец (100г)",	calories=96},
		{str="≈ Судак отварной (100г)",	calories=97},
		{str="≈ Манная каша мол. (100г)",	calories=98},
		{str="≈ Овощное рагу (100г)",	calories=99},
		{str="≈ Карп отварной (100г)",	calories=102},
		{str="≈ Фруктовый салат (100г)",	calories=103},
		{str="≈ Филе индейки (100г)",	calories=104},
		{str="≈ Свинной балык (100г)",	calories=105},
		{str="≈ Плов с курицей (100г)",	calories=106},
		{str="≈ Рис (100г)",	calories=113},
		{str="≈ Цеппелины (100г)",	calories=117},
		{str="≈ Яичница",	calories=119},
		{str="≈ Икра кабачковая (100г)",	calories=122},
		{str="≈ Майонез японский (100г)",	calories=134},
		{str="≈ Зефир (1шт)",	calories=135},
		{str="≈ Творог (100г)",	calories=136},
		{str="≈ Авокадо ролл",	calories=140},
		{str="≈ Капучино (100г)",	calories=140},
		{str="≈ Лобио (100г)",	calories=141},
		{str="≈ Говядина, язык (100г)",	calories=146},
		{str="≈ Говяжий гуляш (100г)",	calories=148},
		{str="≈ Куриное филе вар. (100г)",	calories=153},
		{str="≈ Картошка жар. (100г)",	calories=154},
		{str="≈ Пицца маргарита (100г)",	calories=157},
		{str="≈ Тефтели (100г)",	calories=159},
		{str="≈ Гречневая каша (100г)",	calories=160},
		{str="≈ Сырок Чудо (40г)",	calories=164},
		{str="≈ Хлеб ржаной (100г)",	calories=165},
		{str="≈ Индейка жареная (100г)",	calories=165},
		{str="≈ Салат мимоза (100г)",	calories=183},
		{str="≈ Долма (100г)",	calories=183},
		{str="≈ Копченая курица (100г)",	calories=184},
		{str="≈ Салат Оливье (100г)",	calories=187},
		{str="≈ Зразы картофельные (100г)",	calories=190},
		{str="≈ Биток свиной (100г)",	calories=195},
		{str="≈ Сардельки (100г)",	calories=198},
		{str="≈ Лосось (201г)",	calories=201},
		{str="≈ Сметана 20% (100г)",	calories=204},
		{str="≈ Сливки (100г)",	calories=206},
		{str="≈ Паста болонез (100г)",	calories=208},
		{str="≈ Азу (100г)",	calories=214},
		{str="≈ Хлеб черный (100г)",	calories=214},
		{str="≈ Цукаты (100г)",	calories=216},
		{str="≈ Салат столичный (100г)",	calories=217},
		{str="≈ Сельдь соленая (100г)",	calories=217},
		{str="≈ Жульен грибной (100г)",	calories=219},
		{str="≈ Салат цезарь (100г)",	calories=221},
		{str="≈ Омлет (100г)",	calories=222},
		{str="≈ Светлое пиво (0,5л)",	calories=225},
		{str="≈ Хлеб овсяный (100г)",	calories=226},
		{str="≈ Рагу из баранины (100г)",	calories=226},
		{str="≈ Пломбир (100г)",	calories=227},
		{str="≈ Гамбургер",	calories=229},
		{str="≈ Жаркое из свинины (100г)",	calories=233},
		{str="≈ Батон (100г)",	calories=235},
		{str="≈ Лаваш (100г)",	calories=236},
		{str="≈ Водка 40% (100г)",	calories=237},
		{str="≈ Бастурма (100г)",	calories=240},
		{str="≈ Хамон (100г)",	calories=241},
		{str="≈ Хлеб пшеничный (100г)",	calories=242},
		{str="≈ Сосиски русские (100г)",	calories=243},
		{str="≈ Равиоли (100г)",	calories=245},
		{str="≈ Красная икра (100г)",	calories=249},
		{str="≈ Шаурма (100г)",	calories=250},
		{str="≈ Колбаса вареная (100г)",	calories=257},
		{str="≈ Сосиски куриные (100г)",	calories=259},
		{str="≈ Котлеты (100г)",	calories=260},
		{str="≈ Изюм (100г)",	calories=262},
		{str="≈ Чизбургер",	calories=264},
		{str="≈ Сосиски мол. (100г)",	calories=270},
		{str="≈ Ветчина (100г)",	calories=270},
		{str="≈ Мойва копченая (100г)",	calories=270},
		{str="≈ МакНаггетс (100г)",	calories=272},
		{str="≈ Кровянка (100г)",	calories=274},
		{str="≈ Мясо в шубе (100г)",	calories=274},
		{str="≈ Пельмени (100г)",	calories=275},
		{str="≈ Плов со свининой (100г)",	calories=281},
		{str="≈ Лосось гриль (100г)",	calories=283},
		{str="≈ Сырок Дружба (100г)",	calories=287},
		{str="≈ Черная икра (100г)",	calories=289},
		{str="≈ Майонез (100г)",	calories=299},
		{str="≈ Цветочный мед (100г)",	calories=302},
		{str="≈ Картофель фри (100г)",	calories=303},
		{str="≈ Салат Оливье (100г)",	calories=305},
		{str="≈ Скумбрия соленая (100г)",	calories=305},
		{str="≈ Финики (100г)",	calories=306},
		{str="≈ Оладьи с яблоками (100г)",	calories=306},
		{str="≈ Голубцы (100г)",	calories=311},
		{str="≈ Беляш (100г)",	calories=320},
		{str="≈ Оладьи (100г)",	calories=322},
		{str="≈ Омлет с сыром (100г)",	calories=324},
		{str="≈ Колбаса ливерная (100г)",	calories=326},
		{str="≈ Колбаски охотничьи (100г)",	calories=326},
		{str="≈ Пончики (100г)",	calories=329},
		{str="≈ Ватрушка (100г)",	calories=331},
		{str="≈ Блины с маслом (100г)",	calories=332},
		{str="≈ Люля-кебаб (100г)",	calories=339},
		{str="≈ Сушки (100г)",	calories=341},
		{str="≈ Макароны Макфа (100г)",	calories=344},
		{str="≈ Спагетти (100г)",	calories=344},
		{str="≈ Кекс (100г)",	calories=345},
		{str="≈ Пряник (100г)",	calories=350},
		{str="≈ Бефстроганов (100г)",	calories=355},
		{str="≈ Российский сыр (100г)",	calories=360},
		{str="≈ Кукурузные хлопья (100г)",	calories=363},
		{str="≈ Макароны (100г)",	calories=371},
		{str="≈ Бифштекс (100г)",	calories=384},
		{str="≈ Сухари (100г)",	calories=386},
		{str="≈ Сахар-песок  (100г)",	calories=398},
		{str="≈ Козинаки (100г)",	calories=419},
		{str="≈ Овсяное печенье (100г)",	calories=440},
		{str="≈ Лапша Роллтон  (100г)",	calories=448},
		{str="≈ Торт муравейник (100г)",	calories=452},
		{str="≈ Шницель (100г)",	calories=456},
		{str="≈ Лазанья (100г)",	calories=460},
		{str="≈ Фуа-гра (100г)",	calories=462},
		{str="≈ Торт Медовик  (100г)",	calories=478},
		{str="≈ Попкорн (100г)",	calories=480},
		{str="≈ Твикс",	calories=483},
		{str="≈ Сникерс",	calories=497},
		{str="≈ Бекон (100г)",	calories=500},
		{str="≈ Биг Мак",	calories=510},
		{str="≈ Чипсы Lays Max (100г)",	calories=510},
		{str="≈ Халва (100г)",	calories=522},
		{str="≈ Шоколад KitKat",	calories=524},
		{str="≈ Роял Чизбургер (100г)",	calories=530},
		{str="≈ Тирамису (100г)",	calories=540},
		{str="≈ Чипсы Pringles (100г)",	calories=540},
		{str="≈ Шоколад (100г)",	calories=546},
		{str="≈ Торт Наполеон (100г)",	calories=552},
		{str="≈ Салями (100г)",	calories=568},
		{str="≈ Гусь жареный (100г)",	calories=620},
		{str="≈ Майонез Евр. (100г)",	calories=665},
		{str="≈ Пельмени жареные (100г)",	calories=764},
		{str="≈ Сало (100г)",	calories=797},
		{str="≈ Биг Тейсти",	calories=850},
    },

    ok='ОК',

    hour='ч.',
    minute='мин.',
    month='мес.',
    day='дней',
    step="шагов",
    km='км',
    minute_format='%d мин.',
    hour_minute_format='%d ч. %d мин.',
    hour_format='%d ч.',

    welcome_use='Добро пожаловать',
    last_week_walked_format='%d шагов пройдено на прошлой неделе.',
    last_week_walked_info_format='Пройдено %d км, сожжено %d ккал.',
    last_month_walked_format='%d шагов пройдено в прошлом месяце.',
    last_month_walked_info_format='Пройдено %d км, сожжено %d ккал.',

    get_over_format=", приблизительно %d грамм жира.",
    click_to_get_help="Узнайте, что вы можете делать с Mi Band.",
    take_a_walk="Пройдитесь с Mi Band.",
    take_a_walk_info="Mi Band будет отслеживать вашу активность и поможет быть здоровым.",
    unlock_hint="Разблокируйте телефон с помощью Mi Band",
    unlock_hint_info="Попрощайтесь с дневной рутиной.",
	no_data_hint_0="Национальный Фонд Сна США рекомендует спать на протяжении 7~9 часов.",
    no_data_hint_1="Повторение - мать учения.",
    no_data_hint_2="Стремитесь к прогрессу а не идеалу.",
    no_data_hint_3="Не важно на сколько медленно вы идете. Вы все еще оставляете других позади, на диване.",
    not_binded_hint="Mi Band не подключен к этому аккаунту, пожалуйста подключите браслет.",
    new_record_info="Вы только что побили рекорд в ходьбе!",
    new_record_format="%d шагов, %s %d",
    today_goal_reached="Поздравляю! Вы достигли заданной цели сегодня.",
    week_continue_reach_goal="Вы достигали заданной цели каждый день на протяжении всей недели! Какая чудесная неделя!",

    -- Continue reach goals string
    challenge_format="Вы достигали заданной цели на протяжении %d дней!",
    personal_best_format="Ваша лучшая продолжительность рекордов - %d дней!",
    continue_with_skips_title="Вы не достигли цели вчера, назовем это Днем Отдыха ;)",
    continue_with_skips_title_today="Вы сегодня не достигли цели, назовем это Днем Отдыха ;)",
    personal_best_with_skips_format="Вы только что сделали лучший рекорд за %d дней! У вас осталось %d Дней Отдыха ;)",
    continue_used_n_skips_format="Вы достигали цели на протяжении %d дней! У вас все еще есть %d Дней Отдыха ;)",
    continue_used_0_skips_format="Вы достигали цели на протяжении %d дней! У вас не осталось Дней Отдыха.",
    personal_best_on_skip_day_title="Вы достигали цели на протяжении %d дней! В награду вы получаете один День Отдыха ;) Вы можете воспользоваться им в день, когда вы не достигли цели.",
    personal_best_on_skip_day_info="Вы получите один День Отдыха за достижения цели каждые 7 дней подряд. Мы автоматически используем его если вы не достигните вашей цели. Один День Отдыха приравнивается одному дню.",
    manual_lazy_title="Вы не достигли сегодня своей цели, назовем это Днем Отдыха?",
    manual_lazy_subtitle="Этот день будет вам прощен если вы согласитесь.",
    manual_lazy_title_used="Продолжительность достижения цели сохранена. Наслаждайтесь!",
    manual_lazy_subtitle_used="Продолжительность достижения будет засчитана позже.",
    manual_fail_ytd_title = "К сожалению, продолжительность достижений прервана вчера.",
    manual_fail_ytd_subtitle = "Продолжительность достижений до вчера - %d.",

    active_time_format_0="%d м.",
    active_time_format_1="%d ч.",
    active_time_format_2="%d ч. %d мин.",
    activie_run_format_0="Пробежали %s. Отличная работа!",
    activie_run_format_1="Пробежали %s. Супер результат!",
    activie_run_format_2="Пробежали %s, Нереальная выносливость, вы молодец!",
    activie_run_consumed="Сожжено %d ккал %s",

    get_distance_format=" всего %d м.",
    activity_walk_format="%s Пройдено %d шагов, %s",
    activity_walk_consumed_format="Сожжено %d ккал %s", 
    activity_rope_skipping_format="%s Прыгали на скакалке %d раз.",
    activity_situp_format="%s Сделали упражнение для пресса %d раз.",
    activity_consumed_format="Сожжено %d ккал %s",
    activity_activity_format="%s %s тренировки, %s",
    activity_activity_format_run="%s %s тренировки, пробежали %s",
    last_night_sleeped_good_format="Прошлой ночью вы спали %s \nКакой чудесный сон!",
    last_night_sleeped_normal_format="Прошлой ночью вы спали %s",
    deep_sleep_format="В стадии глубокого сна вы находились %s",

    battery_low_info="Низкий заряд, зарядите Mi Band.",
    battery_very_low_info="Подключите к зарядному устройству",

    cannot_find_bracelet="Не удалось найти ваш Mi Band?",
    cannot_find_bracelet_info="Убедитесь в том, что Mi Band находится близко к телефону.",
    challenge_to_get="%s дней с момента нового рекорда!",
    record_reach_max="Вы побили свой рекорд!",
    new_record_born="Новый рекорд!",

    ---====== Weather tips ===============
    weather_tips_title_0 = "Сильное загрязнение. Постарайтесь остаться дома.",
    weather_tips_title_1 = "Сильное загрязнение. Постарайтесь остаться дома.",
    weather_tips_info = "Дома вы сможете заняться упражнениями для пресса и прыжками со скакалкой!",
}