-------------------------
-- Simplified Chinese Localization String resources
-- Huami Co, ltd. (2014)
-- Herbert dai
-- Calories table added by dezmen3
-- miui.en
-- 20150119
-------------------------
localization_Chinese_table = {
    calories_table={
		{str="≈ Cucumber (100g)",	calories=14},
		{str="≈ Chicken broth (100g)",	calories=15},
		{str="≈ Cabbage (100g)",	calories=16},
		{str="≈ Pickled tomatoes (100g)",	calories=19},
		{str="≈ Mushrooms (100g)",	calories=20},
		{str="≈ Radishes (100g)",	calories=21},
		{str="≈ Eggplant (100g)",	calories=24},
		{str="≈ Pumpkin (100g)",	calories=25},
		{str="≈ Sauerkraut (100g)",	calories=25},
		{str="≈ Mushroom soup (100g)",	calories=26},
		{str="≈ Broccoli (100g)",	calories=27},
		{str="≈ Vegetable soup (100g)",	calories=28},
		{str="≈ Strawberries (100g)",	calories=30},
		{str="≈ Borsch (100g)",	calories=36},
		{str="≈ Miso soup (100g)",	calories=36},
		{str="≈ Beetroot (100g)",	calories=36},
		{str="≈ Apple (100g)",	calories=37},
		{str="≈ Orange (100g)",	calories=38},
		{str="≈ Potato soup (100g)",	calories=39},
		{str="≈ Watermelon (100g)",	calories=39},
		{str="≈ Sorrel soup (100g)",	calories=40},
		{str="≈ Buttermilk 1% (100g)",	calories=40},
		{str="≈ Coca-Cola (100g)",	calories=42},
		{str="≈ 1.5% Milk (100g)",	calories=45},
		{str="≈ Red Bull (100g)",	calories=45},
		{str="≈ Chowder (100g)",	calories=46},
		{str="≈ Peach (100g)",	calories=46},
		{str="≈ Hochland cheese (25g)",	calories=48},
		{str="≈ Cherry (100g)",	calories=52},
		{str="≈ Orange juice (100g)",	calories=54},
		{str="≈ 3.2% milk (100g)",	calories=58},
		{str="≈ Ratatouille (100g)",	calories=60},
		{str="≈ Mashed potatoes (100g)",	calories=65},
		{str="≈ Pea soup (100g)",	calories=66},
		{str="≈ Mango (100g)",	calories=67},
		{str="≈ Lentil Soup (100g)",	calories=68},
		{str="≈ Strawberry jelly (100g)",	calories=69},
		{str="≈ Yogurt 1.5% (100g)",	calories=70},
		{str="≈ Crab sticks (100g)",	calories=73},
		{str="≈ Squid (100g)",	calories=75},
		{str="≈ Champagne (100g)",	calories=76},
		{str="≈ Wine 13% (100g)",	calories=78},
		{str="≈ Cabbage goulash (100g)",	calories=81},
		{str="≈ Boiled potatoes (100g)",	calories=82},
		{str="≈ Absinthe 60% ​​(100g)",	calories=83},
		{str="≈ Milk mashed potatoes (100g)",	calories=85},
		{str="≈ Boiled egg (55g)",	calories=88},
		{str="≈ Banana (100g)",	calories=89},
		{str="≈ Tomato beans (100g)",	calories=92},
		{str="≈ Ketchup (100g)",	calories=93},
		{str="≈ Rice with vegetables (100g)",	calories=94},
		{str="≈ Grain toast (1 slice)",	calories=95},
		{str="≈ Tuna (100g)",	calories=96},
		{str="≈ Boiled walleye (100g)",	calories=97},
		{str="≈ Vegetable stew (100g)",	calories=99},
		{str="≈ Boiled carp (100g)",	calories=102},
		{str="≈ Fruit salad (100g)",	calories=103},
		{str="≈ Turkey fillet (100g)",	calories=104},
		{str="≈ Pork sturgeon (100g)",	calories=105},
		{str="≈ Rice (100g)",	calories=113},
		{str="≈ Zeppelins (100g)",	calories=117},
		{str="≈ Scrambled egg",	calories=119},
		{str="≈ Squash paste (100g)",	calories=122},
		{str="≈ Japanese mayonnaise (100g)",	calories=134},
		{str="≈ Marshmallow (1pc)",	calories=135},
		{str="≈ Cottage cheese (100g)",	calories=136},
		{str="≈ Avocado roll",	calories=140},
		{str="≈ Cappuccino (100g)",	calories=140},
		{str="≈ Lobio (100g)",	calories=141},
		{str="≈ Beef tongue (100g)",	calories=146},
		{str="≈ Beef goulash (100g)",	calories=148},
		{str="≈ Boiled chicken fillet (100g)",	calories=153},
		{str="≈ Fried potato (100g)",	calories=154},
		{str="≈ Pizza Margarita (100g)",	calories=157},
		{str="≈ Meatballs (100g)",	calories=159},
		{str="≈ Buckwheat (100g)",	calories=160},
		{str="≈ Rye bread (100g)",	calories=165},
		{str="≈ Roast turkey (100g)",	calories=165},
		{str="≈ Smoked chicken (100g)",	calories=184},
		{str="≈ The cue pork (100g)",	calories=195},
		{str="≈ Sausages (100g)",	calories=198},
		{str="≈ Salmon (201g)",	calories=201},
		{str="≈ Sour cream 20% (100g)",	calories=204},
		{str="≈ Cream (100g)",	calories=206},
		{str="≈ Pasta Bolognese (100g)",	calories=208},
		{str="≈ Black bread (100g)",	calories=214},
		{str="≈ Candied fruits (100g)",	calories=216},
		{str="≈ Salted herring (100g)",	calories=217},
		{str="≈ Mushroom julienne (100g)",	calories=219},
		{str="≈ Caesar salad (100g)",	calories=221},
		{str="≈ Omelette (100g)",	calories=222},
		{str="≈ Light beer (0.5L)",	calories=225},
		{str="≈ Oat bread (100g)",	calories=226},
		{str="≈ Lamb stew (100g)",	calories=226},
		{str="≈ Sundae (100g)",	calories=227},
		{str="≈ McD Hamburger",	calories=229},
		{str="≈ Roast pork (100g)",	calories=233},
		{str="≈ White bread (100g)",	calories=235},
		{str="≈ Pita bread (100g)",	calories=236},
		{str="≈ Vodka 40% (100g)",	calories=237},
		{str="≈ Basturma (100g)",	calories=240},
		{str="≈ Hamon (100g)",	calories=241},
		{str="≈ Ravioli (100g)",	calories=245},
		{str="≈ Red caviar (100g)",	calories=249},
		{str="≈ Shawarma (100g)",	calories=250},
		{str="≈ Chicken sausages (100g)",	calories=259},
		{str="≈ Cutlets (100g)",	calories=260},
		{str="≈ Raisins (100g)",	calories=262},
		{str="≈ McD Cheeseburger",	calories=264},
		{str="≈ Milk sausages (100g)",	calories=270},
		{str="≈ Ham (100g)",	calories=270},
		{str="≈ Capelin smoked (100g)",	calories=270},
		{str="≈ McD McNuggets (100g)",	calories=272},
		{str="≈ Dumplings (100g)",	calories=275},
		{str="≈ Grilled salmon (100g)",	calories=283},
		{str="≈ Black Caviar (100g)",	calories=289},
		{str="≈ Mayonnaise (100g)",	calories=299},
		{str="≈ Honey (100g)",	calories=302},
		{str="≈ McD Fries (100 g)",	calories=303},
		{str="≈ Dates (100g)",	calories=306},
		{str="≈ Apple pancakes (100g)",	calories=306},
		{str="≈ Stuffed cabbage (100g)",	calories=311},
		{str="≈ Pancakes (100g)",	calories=322},
		{str="≈ Omelet with cheese (100g)",	calories=324},
		{str="≈ Liver sausages (100g)",	calories=326},
		{str="≈ Donuts (100g)",	calories=329},
		{str="≈ Cheesecake (100g)",	calories=331},
		{str="≈ Pancakes with butter (100g)",	calories=332},
		{str="≈ Kebab (100g)",	calories=339},
		{str="≈ Spaghetti (100g)",	calories=344},
		{str="≈ Muffin (100g)",	calories=345},
		{str="≈ Gingerbread (100g)",	calories=350},
		{str="≈ Beef stroganoff (100g)",	calories=355},
		{str="≈ Cornflakes (100g)",	calories=363},
		{str="≈ Pasta (100g)",	calories=371},
		{str="≈ Steak (100g)",	calories=384},
		{str="≈ Crackers (100g)",	calories=386},
		{str="≈ Sugar (100g)",	calories=398},
		{str="≈ Oatmeal cookies (100g)",	calories=440},
		{str="≈ Schnitzel (100g)",	calories=456},
		{str="≈ Lasagne (100g)",	calories=460},
		{str="≈ Foie Gras (100g)",	calories=462},
		{str="≈ Honey cake (100g)",	calories=478},
		{str="≈ Popcorn (100g)",	calories=480},
		{str="≈ Twix",	calories=483},
		{str="≈ Snickers",	calories=497},
		{str="≈ Bacon (100g)",	calories=500},
		{str="≈ McD Big Mac",	calories=510},
		{str="≈ Lays Max chips (100g)",	calories=510},
		{str="≈ KitKat",	calories=524},
		{str="≈ Tiramisu (100g)",	calories=540},
		{str="≈ Pringles (100g)",	calories=540},
		{str="≈ Chocolate (100g)",	calories=546},
		{str="≈ Napoleon cake (100g)",	calories=552},
		{str="≈ Salami (100g)",	calories=568},
		{str="≈ Roast goose (100g)",	calories=620},
		{str="≈ Fried dumplings (100g)",	calories=764},
		{str="≈ McD Big Tasty",	calories=850},
    },

    ok='OK',

    hour='hrs',
    minute='min',
    month='month',
    day='day',
    step="steps",
    km='km',
    minute_format='%d min',
    hour_minute_format='%dh %dm',
    hour_format='%d hrs',

    welcome_use="Welcome",
    last_week_walked_format='You walked %d steps last week.',
    last_week_walked_info_format='Walked %dkm, burned %d cal.',
    last_month_walked_format='You walked %d steps last month.',
    last_month_walked_info_format='Walked %dkm, burned %d cal.',

    get_over_format=", about %d grams of fat",
    click_to_get_help="Learn more about Mi Band",
    take_a_walk="Take a walk with your band",
    take_a_walk_info="Your band keeps track of every step you take throughout the day.",
    unlock_hint="Open sesame!",
    unlock_hint_info="Use your band to unlock your device automatically.",
    no_data_hint_0="The US National Sleep Foundation recommends between 7-9 hours of sleep per night.",
    no_data_hint_1="Repetition is the father of success.",
    no_data_hint_2="Strive for progress, not perfection.",
    no_data_hint_3="No matter how slow you go, you're still lapping everybody on the couch.",
    not_binded_hint="No bands have been added to this account.",
    not_binded_hint_info="You can also click Weight Scale in menu.",
    new_record_info="You set a new record!",
    new_record_format="%d steps, %s %d",
    today_goal_reached="You reached your goal today!",
    week_continue_reach_goal="You",

    challenge_format="You've hit your goal for %d days in a row!",
    personal_best_format="Your longest streak is %d days!",
    continue_with_skips_title="You didn't hit your goal yesterday. Let's call it a Lazy Day ;)",
    continue_with_skips_title_today="You didn't hit your goal today. Let's call it a Lazy Day ;)",
    personal_best_with_skips_format="You have %d Lazy Days left ;)",
    continue_used_n_skips_format="You've hit your goal for %d days in a row! You still have %d Lazy Days",
    continue_used_0_skips_format="You've hit your goal for %d days in a row! You have no Lazy Days left.",
    personal_best_on_skip_day_title="%d day streak! You've earned a Lazy Day!",
    personal_best_on_skip_day_info="After every 7-day streak you earn a Lazy Day. You can use Lazy Days to cover days when you don't hit your goal.",
    manual_lazy_title="You didn't hit your goal today.",
    manual_lazy_subtitle="Your streak will continue if you mark today as a Lazy Day.",
    manual_lazy_title_used="Today is a Lazy Day.",
    manual_lazy_subtitle_used="You can earn more Lazy Days by breaking personal records.",
    manual_fail_ytd_title = "You ended your streak yesterday.",
    manual_fail_ytd_subtitle = "Streak was %d long.",

    active_time_format_0="%dm",
    active_time_format_1="%dh",
    active_time_format_2="%dh %dm",
    activie_run_format_0="Ran %s. Great job!",
    activie_run_format_1="Ran %s. You're doing great!",
    activie_run_format_2="Ran %s.",
    activie_run_consumed="Burned %d cal. %s",

    get_distance_format="about %dm.",
    activity_walk_format="%s Walked %d steps, %s",
    activity_walk_consumed_format="Burned %d cal %s.",
    activity_rope_skipping_format="%s jumped rope %d times",
    activity_situp_format="%s %d sit-ups",
    activity_consumed_format="Burned %d cal %s",
    activity_activity_format="%s Worked out for %s, %s",
    activity_activity_format_run="%s Worked out for %s, ran %s",
    last_night_sleeped_good_format="You slept for %s last night.",
    last_night_sleeped_normal_format="You slept for %s last night.",
    deep_sleep_format="Deep sleep lasted %s.",

    battery_low_info="Charge your band",
    battery_very_low_info="Your band's battery is running low.",

    cannot_find_bracelet="Can't find your band.",
    cannot_find_bracelet_info="Make sure your band's battery is charged.",

    bracelet_disconnect = "Unable to connect？click to get help.",

    challenge_to_get="%s days from setting a new record!",
    record_reach_max="You've tied your existing record!",
    new_record_born="You set a new record.",

    ---====== Weather tips ===============
    weather_tips_title_0 = "Heavy pollution, try to stay indoors",
    weather_tips_title_1 = "Heavy pollution, try to stay indoors",
    weather_tips_info = "Sit-ups or jumping rope are great indoor exercises!",

    ---------------Weight scale -------------------
    welcome_use_weight_scale = "Welcome use weight scale",
    welcome_use_weight_scale_not_bind = "Click to bind weight scale",
    welcome_use_mi_health="Welcome use MI Sports",

    select_devices="Select devices to bind now"
}
