-------------------------
-- English Localization String resources
-- Huami Co, ltd. (2014)
-- Herbert dai
-- 20140731
-------------------------
localization_English_table = {
    calories_table={

    },

    ok='OK',

    hour='hrs',
    minute='min',
    month='month',
    day='day',
    step="steps",
    km='km',
    minute_format='%dmin',
    hour_minute_format='%dh %dm',
    hour_format='%dhrs',

    welcome_use="Welcome",
    last_week_walked_format='You walked %d steps last week.',
    last_week_walked_info_format='Walked %dkm, burned %dcal.',
    last_month_walked_format='You walked %d steps last month.',
    last_month_walked_info_format='Walked %dkm, burned %dcal.',

    get_over_format=", about %d grams of fat.",
    click_to_get_help="Learn more about Mi Band",
    take_a_walk="Take a walk with your band",
    take_a_walk_info="Your band keeps track of every step you take throughout the day.",
    unlock_hint="Open sesame!",
    unlock_hint_info="Use your band to unlock your device automatically.",
    no_data_hint_0="The US National Sleep Foundation recommends between 7-9 hours of sleep per night.",
    no_data_hint_1="Repetition is the father of success.",
    no_data_hint_2="Strive for progress, not perfection.",
    no_data_hint_3="No matter how slow you go, you're still lapping everybody on the couch.",
    not_binded_hint="No bands have been added to this account.",
    new_record_info="You set a new record!",
    new_record_format="%d steps, %s %d",
    today_goal_reached="You reached your goal today!",
    week_continue_reach_goal="You",

    challenge_format="You've hit your goal for %d days in a row!",
    personal_best_format="Your longest streak is %d days!",
    continue_with_skips_title="You didn't hit your goal yesterday. Let's call it a Lazy Day ;)",
    continue_with_skips_title_today="You didn't hit your goal today. Let's call it a Lazy Day ;)",
    personal_best_with_skips_format="You have %d Lazy Days left ;)",
    continue_used_n_skips_format="You've hit your goal for %d days in a row! You still have %d Lazy Days",
    continue_used_0_skips_format="You've hit your goal for %d days in a row! You have no Lazy Days left.",
    personal_best_on_skip_day_title="%d day streak! You've earned a Lazy Day!",
    personal_best_on_skip_day_info="After every 7-day streak you earn a Lazy Day. You can use Lazy Days to cover days when you don't hit your goal.",
    manual_lazy_title="You didn't hit your goal today.",
    manual_lazy_subtitle="Your streak will continue if you mark today as a Lazy Day.",
    manual_lazy_title_used="Today is a Lazy Day.",
    manual_lazy_subtitle_used="You can earn more Lazy Days by breaking personal records.",
    manual_fail_ytd_title = "You ended your streak yesterday.",
    manual_fail_ytd_subtitle = "Streak was %d long.",

    active_time_format_0="%dm",
    active_time_format_1="%dh",
    active_time_format_2="%dh %dm",
    activie_run_format_0="Ran %s. Great job!",
    activie_run_format_1="Ran %s. You're doing great!",
    activie_run_format_2="Ran %s.",
    activie_run_consumed="Burned %dcal. %s",

    get_distance_format="about %dm.",
    activity_walk_format="%s Walked %d steps, %s",
    activity_walk_consumed_format="Burned %dcal%s.",
    activity_rope_skipping_format="%s jumped rope %d times",
    activity_situp_format="%s %d sit-ups",
    activity_consumed_format="Burned %dcal %s",
    activity_activity_format="%s Worked out for %s, %s",
    activity_activity_format_run="%s Worked out for %s, ran %s",
    last_night_sleeped_good_format="You slept for %s last night.",
    last_night_sleeped_normal_format="You slept for %s last night.",
    deep_sleep_format="Deep sleep lasted %s.",

    battery_low_info="Charge your band",
    battery_very_low_info="Your band's battery is running low.",

    cannot_find_bracelet="Can't find your band.",
    cannot_find_bracelet_info="Make sure your band's battery is charged.",
    challenge_to_get="%s days from setting a new record!",
    record_reach_max="You've tied your existing record!",
    new_record_born="You set a new record.",

    ---====== Weather tips ===============
    weather_tips_title_0 = "Heavy pollution, try to stay indoors",
    weather_tips_title_1 = "Heavy pollution, try to stay indoors",
    weather_tips_info = "Sit-ups or jumping rope are great indoor exercises!",
	
	---------------Weight scale -------------------
    welcome_use_weight_scale = "Welcome use weight scale",
    welcome_use_weight_scale_not_bind = "Click to bind weight scale",
    welcome_use_mi_health="Welcome use MI health",
}


localization_French_table = {
    calories_table={
        {str="≈1 duo d'oeufs durs",	calories=96},
        {str="≈1 tranche de pain",	calories=100},
        {str="≈1 canette de thé glacé",	calories=112},
        {str="≈1 omelette",	calories=118},
        {str="≈2 brochettes",	calories=124},
        {str="≈1 canette de Coca-Cola",	calories=153},
        {str="≈3 brochettes",	calories=186},
        {str="≈2 duo d'oeufs durs",	calories=192},
        {str="≈2 tranches de pain",	calories=200},
        {str="≈1 bol de riz",	calories=210},
        {str="≈1 pain",	calories=221},
        {str="≈1 paquet de dragibus",	calories=223},
        {str="≈2 canettes de thé glacé",	calories=224},
        {str="≈1 petite frite",	calories=224},
        {str="≈1 tartelette",	calories=224},
        {str="≈2 omelettes",	calories=236},
        {str="≈4 brochettes",	calories=248},
        {str="≈1 hamburger",	calories=260},
        {str="≈1 beignet",	calories=270},
        {str="≈1 petit pain de viande",	calories=272},
        {str="≈3 duo d'oeufs durs",	calories=288},
        {str="≈1 cône",	calories=290},
        {str="≈3 tranches de pain",	calories=300},
        {str="≈2 canettes de Coca-Cola",	calories=306},
        {str="≈1 moyenne frite",	calories=328},
        {str="≈3 omelettes",	calories=354},
        {str="≈1 tartelette aux œufs",	calories=375},
        {str="≈4 tranches de pain",	calories=400},
        {str="≈1 grande frite",	calories=402},
        {str="≈2 bols de riz",	calories=420},
        {str="≈2 pains",	calories=442},
        {str="≈2 paquet de dragibus",	calories=446},
        {str="≈2 tartelettes",	calories=448},
        {str="≈1 paquet de nouilles instantanées",	calories=470},
        {str="≈5 tranches de pain",	calories=500},
        {str="≈1 assiette de riz frit",	calories=516},
        {str="≈2 hamburgers",	calories=520},
        {str="≈2 beignets",	calories=540},
        {str="≈2 petits pains de viande",	calories=544},
        {str="≈2 cônes",	calories=580},
        {str="≈1 bol de nouilles instantanées",	calories=581},
        {str="≈1 bol de nouilles au boeuf",	calories=593},
        {str="≈10 brochettes",	calories=620},
        {str="≈3 bols de riz",	calories=630},
        {str="≈3 pains",	calories=663},
        {str="≈2 tartelettes aux œufs",	calories=750},
        {str="≈3 beignets",	calories=810},
        {str="≈3 petits pains de viande",	calories=816},
    },

    ok='OK',

    hour='h',
    minute='min',
    month='mois',
    day='jour',
    step="pas",
    km='KM',
    minute_format='%dmin',
    hour_minute_format='%dh%dmin',
    hour_format='%dh',

    welcome_use="Salut, je suis ton Mi Band.",
    last_week_walked_format='La semaine dernier, tu as marché %d pas.',
    last_week_walked_info_format='%d km parcourus, %d cal. brûlées',
    last_month_walked_format='Le mois dernier, tu as marché %d pas.',
    last_month_walked_info_format='%d km parcourus, %d cal. brûlées',

    get_over_format=", environ %d gr de graisse.",
    click_to_get_help="Comment mieux utiliser le Mi Band.",
    take_a_walk="Va faire un tour avec Mi Band.",
    take_a_walk_info="Mi Band suivra ton activité et t'aidera à être en meilleur santé.",
    unlock_hint="Dévérouiller le téléphone avec votre Mi Band",
    unlock_hint_info="Dis au revoir au temps d'avant.",
    no_data_hint_0="Continuer de bouger, fais du sport une partie de ta vie.",
    no_data_hint_1="Tu veux rester heureux? Alors cours.",
    no_data_hint_2="L'entrainement cardio te rendra léger et frais chaque jour! ",
    no_data_hint_3="Un adulte normal passe 15%-20% de son temps de sommeil en phase de sommeil profond. ",
    not_binded_hint="Aucun Mi Band n'est associé à ce compte, en appairer un. ",
    new_record_info="WoW! Tu viens d'exploser un record en marchant.",
    new_record_format="Nouveau record, %d pas, %s %d",
    today_goal_reached="Félicitation! You have achieved your goal today. ",
    week_continue_reach_goal="Tu as atteint ton objectif chaque jour de cette semaine! Quelle semaine incroyable!",
    challenge_format="Tu as atteint ton objectif %d jours d'affilé!",
    personal_best_format="Ton meilleur record est %d jours!",
    active_time_format_0="%dh",
    active_time_format_1="%dh",
    active_time_format_2="%dh%dmin",
    activie_run_format_0="Couru %s. Bon boulot!",
    activie_run_format_1="Couru %s. Tu fais des micracles!",
    activie_run_format_2="Couru %s. Incroyable endurance!",
    activie_run_consumed="%d cal brûlées. %s",

    get_distance_format=", pour un total de %dm.",
    activity_walk_format="%s a marché %d pas %s",
    activity_walk_consumed_format="%d cal brûlées %s",

    activity_activity_format="%s %s d'entrainement %s",
    last_night_sleeped_good_format="La nuit dernière, tu as dormi %dh%dmin. Quelle bonne nuit!",
    last_night_sleeped_normal_format="La nuit dernière, tu as dormi %dh%dmin.",
    deep_sleep_format="En phase de sommeil profond pendant %dh%dmin.",

    battery_low_info="Batterie faible, branche ton Mi Band.",
    battery_very_low_info="Brancher au secteur",

    cannot_find_bracelet="Impossible de trouver ton Mi Band?",
    cannot_find_bracelet_info="Assure toi que ton Mi Band soit chargé et proche du téléphone.",

    challenge_to_get="A %s jours de battre un nouveau record!",
    record_reach_max="Tu as atteint ton meilleur record!",
    new_record_born="Nouveau record!",
 }
localization_Portuguese_table = {
    calories_table={

    },

    ok='OK',

    hour='hora',
    minute='min',
    month='mês',
    day='dia',
    step="passos",
    km='km',
    minute_format='%d min.',
    hour_minute_format='%d hora(s) %d min.',
    hour_format='%d horas',

    welcome_use="Bem-vindo",
    last_week_walked_format='Na semana passada caminhou %d passos.',
    last_week_walked_info_format='Caminhou %d km. Queimou %d calorias',
    last_month_walked_format='No mês passado caminhou %d passos.',
    last_month_walked_info_format='Caminhou %d km. Queimou %d calorias',

    get_over_format=", cerca de %d gramas de gordura.",
    click_to_get_help="Saiba mais acerca da MiBand",
    take_a_walk="Caminhe com a MiBand",
    take_a_walk_info="A MiBand controla todos seus passos.",
    unlock_hint="Desbloqueie o telefone com a MiBand!",
    unlock_hint_info="Use a MiBand para desbloquear o telefone.",
    no_data_hint_0="Durma entre 7 a 9 horas.",
    no_data_hint_1="Com empenho nada o segura.",
    no_data_hint_2="Passo a passo alcança o objectivo.",
    no_data_hint_3="Mesmo devagar, continue.",
    not_binded_hint="Adicione a MiBand.",
    new_record_info="Novo recorde, continue!",
    new_record_format="Novo recorde %d passos, %s %d",
    today_goal_reached="Hoje alcançou o objectivo!",
    week_continue_reach_goal="Que semana brutal! Alcançou o objectivo todos os dias da semana!",

    -- Continue reach goals string
    challenge_format="Alcançou o objectivo durante %d dias seguidos!",
    personal_best_format="A melhor série foi de %d dias!",
    continue_with_skips_title="Ontem o objectivo ficou por cumprir. Foi dia de descanso.",
    continue_with_skips_title_today="Hoje o objectivo ficou por cumprir. Foi dia de descanso.",
    personal_best_with_skips_format="Restam %d dias de descanso.",
    continue_used_n_skips_format="Alcançou o objectivo %d dias seguidos! Restam %d dias de descanso",
    continue_used_0_skips_format="Alcançou o objectivo %d dias seguidos! Acabaram os dias de descanso.",
    personal_best_on_skip_day_title="%d dia da série! Ganhou um dia de descanso!",
    personal_best_on_skip_day_info="Depois de uma série de 7 dias, ganha um dia de descanso.",
    manual_lazy_title="Hoje o objectivo ficou por cumprir.",
    manual_lazy_subtitle="A série continua se marcar o dia de hoje como descanso.",
    manual_lazy_title_used="Hoje vai descansar.",
    manual_lazy_subtitle_used="Pode ganhar dias de descanso ao quebrar os recordes pessoais.",
    manual_fail_ytd_title = "Terminou a série ontem.",
    manual_fail_ytd_subtitle = "A série durou %d",

    active_time_format_0="%d hora(s)m",
    active_time_format_1="%d hora(s)",
    active_time_format_2="%d hora %d min.",
    activie_run_format_0="Correu %s. Excelente!",
    activie_run_format_1="Correu %s. Fenomenal!",
    activie_run_format_2="Correu %s. Que endurance brutal",
    activie_run_consumed="Queimou %d calorias %s",

    get_distance_format="cerca de %d metros",
    activity_walk_format="%s Caminhou %d passos, %s",
    activity_walk_consumed_format="Queimou %d calorias %s",

    activity_rope_skipping_format="%s Saltou à corda %d vezes",
    activity_situp_format="%s Fez %d abdominais",
    activity_consumed_format="Queimou %d calorias %s",

    activity_activity_format="%s Total de %s, %s",
    activity_activity_format_run="%s Total de %s, correu %s",
    last_night_sleeped_good_format="A noite passada dormiu %s",
    last_night_sleeped_normal_format="A noite passada dormiu %s",
    deep_sleep_format="O sono profundo durou %s",

    battery_low_info="Carregue a MiBand",
    battery_very_low_info="A MiBand tem a bateria fraca",

    cannot_find_bracelet="Erro ao encontrar a MiBand",
    cannot_find_bracelet_info="Certifique-se que a bateria da MiBand tem carga",

    challenge_to_get="%s dias depois do novo recorde",
    record_reach_max="Igualou o recorde existente",
    new_record_born="Atingiu um novo recorde",

    ---====== Weather tips ===============
    weather_tips_title_0 = "Mau tempo, fique em casa",
    weather_tips_title_1 = "Mau tempo, fique em casa",
    weather_tips_info = "Em casa faça abdominais e salte à corda!",
}
 
localization_Spanish_table = {
    calories_table={

    },

    ok='OK',

    hour='hrs',
    minute='min',
    month='mes',
    day='día',
    step="pasos",
    km='Km',
    minute_format='%d min',
    hour_minute_format='%dh %dm',
    hour_format='%dhrs',

    welcome_use="Bienvenido",
    last_week_walked_format='Ha caminado %d pasos en la útima semana.',
    last_week_walked_info_format='Ha caminado %dKm, consumidas %dkcal.',
    last_month_walked_format='Ha caminado %d pasos en el último mes.',
    last_month_walked_info_format='Ha caminado %dKm, consumidas %dkcal.',

    get_over_format=", unos %d gramos de grasa.",
    click_to_get_help="Descubra más sobre Mi Band.",
    take_a_walk="Dé un paseo con su Mi Band.",
    take_a_walk_info="Mi Band realizará un seguimiento de sus actividades y le ayudará a ser más saludable.",
    unlock_hint="Pase de las contraseñas",
    unlock_hint_info="Use su Mi Band para desbloquear su teléfono automáticamente cuando lo coja",
    no_data_hint_0="La Fundación Nacional del Sueño de EEUU recomienda entre 7-9 horas de sueño cada noche.",
    no_data_hint_1="La repetición es el padre de éxito.",
    no_data_hint_2="Lucha por el progreso, no la perfección.",
    no_data_hint_3="No importa lo lento que vaya, usted todavía haciendo más que el que está tirado en el sofá.",
    not_binded_hint="No se ha añadido ninguna Mi Band a esta cuenta.",
    new_record_info="¡Acaba de batir un récord!",
    new_record_format="%d pasos, %s %d",
    today_goal_reached="¡Ha logrado su objetivo de hoy!",
    week_continue_reach_goal="¡Ha alcanzado su meta todos los días durante una semana! ¡Bien hecho!",
    
	challenge_format="¡Ha alcanzado su meta durante %d día(s)!",
    personal_best_format="¡Su récord más alto es de %d día(s)!",
    continue_with_skips_title="No alcanzó su objetivo de ayer, pero no te preocupes, hemos utilizado un comodín para encubrirle ;)",
	continue_with_skips_title_today="Hoy no consiguió su objetivo. Digamos que ha sido un día de descanso ;)",
    personal_best_with_skips_format="¡Acaba de hacer el registro más alto durante %d días! Y además, le quedan %d comodines restantes ;)",
    continue_used_n_skips_format="¡Ha alcanzado su meta durante %d días! Y aún le quedan %d comodines ;)",
    continue_used_0_skips_format="¡Ha alcanzado su meta durante %d días! Ya no le quedan más comodines.",
    personal_best_on_skip_day_title="¡Ha alcanzado su meta durante %d días! Para recompensarte, te damos un comodín como regalo ;) Puede usarlos cuando no alcance su meta por un día con cada comodín.",
    personal_best_on_skip_day_info="Ganará un comodín una vez que alcance su objetivo durante 7 días seguidos. Los usaremos de forma automática cuando no alcance una meta. Un comodín se cambia por un día.",
	manual_lazy_title="Hoy no consiguió su objetivo. ¿Diría que ha sido un día de descanso?",
    manual_lazy_subtitle="La racha se ocultará si lo confirma.",
    manual_lazy_title_used="Hoy es día de descanso, ¡Disfrutelo!",
    manual_lazy_subtitle_used="La racha se añadirá si alcanza el objetivo más tarde.",
    manual_fail_ytd_title = "Lo siento, la racha se rompió ayer.",
    manual_fail_ytd_subtitle = "Su racha hasta antes de ayer %d.",
	
    active_time_format_0="%d min",
    active_time_format_1="%d hr",
    active_time_format_2="%dh %dm",
    activie_run_format_0="Ha corrido %s. ¡Buen trabajo!",
    activie_run_format_1="Ha corrido %s. ¡Lo está haciendo fenomenal!",
    activie_run_format_2="Ha corrido %s",
    activie_run_consumed="Ha consumido %dkcal. %s",

    get_distance_format=", unos %dm.",
    activity_walk_format="%s ha caminado %d pasos %s",
    activity_walk_consumed_format="Consumidas %dkcal %s",
    activity_rope_skipping_format="%s ha realizado %d salto(s) a la comba",
    activity_situp_format="%s ha realizado %d abdominales",
    activity_consumed_format="Consumidas %dkcal %s",
    activity_activity_format="%s ha hecho ejercicio durante %s",
	activity_activity_format_run="%s ha hecho ejercicio durante %s, corrió %s",
    last_night_sleeped_good_format="Ha dormido %s durante la última noche.",
    last_night_sleeped_normal_format="Ha dormido %s durante la última noche.",
    deep_sleep_format="En fase de sueño profundo hasta %s.",

    battery_low_info="Cargue su Mi Band",
    battery_very_low_info="La batería de su Mi Band está muy baja",

    cannot_find_bracelet="No se puede detectar su Mi Band",
    cannot_find_bracelet_info="Asegúrese de que la batería de su Mi Band está cargada.",
    challenge_to_get="%s días después de hacer un nuevo récord!",
    record_reach_max="¡Ha alcanzado su mayor récord!",
    new_record_born="¡Nuevo récord!",
	
	    ---====== Weather tips ===============
    weather_tips_title_0 = "Gran contaminación, intente estar a cubierto.",
    weather_tips_title_1 = "Gran contaminación, intente estar a cubierto.",
    weather_tips_info = "¡Hacer abdominales o saltar la cuerda son grandes deportes de interior!",
 }


localization_Croatian_table = {
	calories_table={
	
	},
	
	ok='U redu',
	
	hour='sati',
	minute='min',
	month='mjesec',
	day='dan',
	step="korak",
	km='KM',
	minute_format='%d min',
	hour_minute_format='%d sati %d min',
	hour_format='%d sati',
	
	welcome_use="Pozdrav, Ja sam tvoj Mi Band.",
	last_week_walked_format='Prošli tjedan, prohodali ste %d koraka.',
	last_week_walked_info_format='Prohodano %d km, potrošeno %d kal.',
	last_month_walked_format='Prošli mjesec, prohodali ste %d koraka.',
	last_month_walked_info_format='Prohodano %d km, potrošeno %d kal.',
	
	get_over_format=", O %d grama ili masti.",
	click_to_get_help="Saznajte što sve možete s Mi Band.",
	take_a_walk="Prošetajte s Mi Band.",
	take_a_walk_info="Mi Band će pratiti vaše aktivnosti i pomoći vam da se osjećate zdravije.",
	unlock_hint="Otključajte telefon vašim Mi Band,",
	unlock_hint_info="recite \"Zbogom\" starim vremenima.",
	no_data_hint_0="Nastavite se kretati, neka sport postane dijelom vašeg života.",
	no_data_hint_1="Želite oststi sretni? Samo trčite.",
	no_data_hint_2="Kardio vježba će vam omogućiti da se osjećate laganije i svježe svaki dan! ",
	no_data_hint_3="Normalna odrasla troši 15% -20% ukupnog vremena sna u dubokoj fazi sna. ",
	not_binded_hint="Nijedan Mi Band nije povezan na ovaj račun, povežite jedan sada. ",
	new_record_info="WoW! Oborili ste rekord u hodanju.",
	new_record_format="Novi rekord, %d koraka, %s %d",
	today_goal_reached="Čestitke! Postigli ste danjašnji cilj. ",
	week_continue_reach_goal="Postigli ste cilj svakog dana ovog tjedna! Stvarno fantastičan tjedan!",
	challenge_format="Postigli ste svoj cilj za %d dan(a)!",
	personal_best_format="Vaš najveći rekord je %d dan(a)!",
	active_time_format_0="%d sati",
	active_time_format_1="%d sati",
	active_time_format_2="%d sati %d min",
	activie_run_format_0="Trčano %s. Dobro je!",
	activie_run_format_1="Trčano %s. Ide vam fantastično!",
	activie_run_format_2="Trčano %s, Nevjerojatno ste izdržljivi!",
	activie_run_consumed="Potrošeno %d kal. %s",
	
	get_distance_format=", ukupno od %d m.",
	activity_walk_format="%s Prohodano %d koraka %s",
	activity_walk_consumed_format="Potrošeno %d kal %s",
	
	activity_activity_format="%s Napravljeno %s %s",
	last_night_sleeped_good_format="Prošle noći ste spavali %d sati %d min. Sad ste stvarno naspavani!",
	last_night_sleeped_normal_format="Prošle noći ste spavali %d sati %d min.",
	deep_sleep_format="Faza dubokog sna je bila %d sati %d min.",
	
	battery_low_info="Slaba baterija, stavite Mi Band na punjenje.",
	battery_very_low_info="Priključite na punjač",
	
	cannot_find_bracelet="Ne možete pronaći svoj Mi Band?",
	cannot_find_bracelet_info="Uvjerite se da vaš MiBand ima energije i nalazi se u blizini vašeg telefona.",
	
	challenge_to_get="%s dana od postizanja novog rekorda!",
	record_reach_max="Postigli ste svoj najveći novi rekord!",
	new_record_born="Novi rekord!",
 }

localization_Russian_table = {
    calories_table={
		{str="≈ Огурец грунт. (100г)",	calories=14},
		{str="≈ Бульон куриный (100г)",	calories=15},
		{str="≈ Капуста пекинская (100г)",	calories=16},
		{str="≈ Томаты соленые (100г)",	calories=19},
		{str="≈ Квас (100г)",	calories=20},
		{str="≈ Шампиньоны (100г)",	calories=20},
		{str="≈ Редис (100г)",	calories=21},
		{str="≈ Баклажаны (100г)",	calories=24},
		{str="≈ Тыква (100г)",	calories=25},
		{str="≈ Квашеная капуста (100г)",	calories=25},
		{str="≈ Айран (100г)",	calories=26},
		{str="≈ Грибной суп (100г)",	calories=26},
		{str="≈ Брокколи (100г)",	calories=27},
		{str="≈ Овощной суп (100г)",	calories=28},
		{str="≈ Клубника (100г)",	calories=30},
		{str="≈ Щи (100г)",	calories=31},
		{str="≈ Борщ (100г)",	calories=36},
		{str="≈ Суп мисо (100г)",	calories=36},
		{str="≈ Свекольник (100г)",	calories=36},
		{str="≈ Яблоко (100г)",	calories=37},
		{str="≈ Апельсин (100г)",	calories=38},
		{str="≈ Картофельный суп (100г)",	calories=39},
		{str="≈ Арбуз (100г)",	calories=39},
		{str="≈ Суп щавелевый (100г)",	calories=40},
		{str="≈ Простокваша 1% (100г)",	calories=40},
		{str="≈ Рассольник (100г)",	calories=42},
		{str="≈ Кока-Кола (100г)",	calories=42},
		{str="≈ Молоко 1.5% (100г)",	calories=45},
		{str="≈ Red Bull (100г)",	calories=45},
		{str="≈ Уха (100г)",	calories=46},
		{str="≈ Персик (100г)",	calories=46},
		{str="≈ Сыр Хохланд (25г)",	calories=48},
		{str="≈ Вишня (100г)",	calories=52},
		{str="≈ Апельсиновый сок (100г)",	calories=54},
		{str="≈ Кефир 3.2% (100г)",	calories=56},
		{str="≈ Окрошка (100г)",	calories=57},
		{str="≈ Молоко 3.2% (100г)",	calories=58},
		{str="≈ Аджика (100г)",	calories=59},
		{str="≈ Рататуй (100г)",	calories=60},
		{str="≈ Пюре с мол. (100г)",	calories=65},
		{str="≈ Гороховый суп (100г)",	calories=66},
		{str="≈ Манго (100г)",	calories=67},
		{str="≈ Овсяная каша (100г)",	calories=68},
		{str="≈ Суп из чечевицы (100г)",	calories=68},
		{str="≈ Клубничное желе (100г)",	calories=69},
		{str="≈ Солянка сборная (100г)",	calories=69},
		{str="≈ Йогурт 1.5% слад. (100г)",	calories=70},
		{str="≈ Крабовые палочки (100г)",	calories=73},
		{str="≈ Суп харчо (100г)",	calories=75},
		{str="≈ Кальмары (100г)",	calories=75},
		{str="≈ Шампанское (100г)",	calories=76},
		{str="≈ Вино 13% (100г)",	calories=78},
		{str="≈ Вареники с капустой (100г)",	calories=79},
		{str="≈ Гуляш с капустой (100г)",	calories=81},
		{str="≈ Картофель отварной (100г)",	calories=82},
		{str="≈ Абсент 60% (100г)",	calories=83},
		{str="≈ Пюре с мол.и масл. (100г)",	calories=85},
		{str="≈ Яйцо вареное (55г)",	calories=88},
		{str="≈ Банан (100г)",	calories=89},
		{str="≈ Кабачковая икра (100г)",	calories=90},
		{str="≈ Фасоль в томате (100г)",	calories=92},
		{str="≈ Кетчуп (100г)",	calories=93},
		{str="≈ Рис с овощами (100г)",	calories=94},
		{str="≈ Зерновой тост (1шт)",	calories=95},
		{str="≈ Тунец (100г)",	calories=96},
		{str="≈ Судак отварной (100г)",	calories=97},
		{str="≈ Манная каша мол. (100г)",	calories=98},
		{str="≈ Овощное рагу (100г)",	calories=99},
		{str="≈ Карп отварной (100г)",	calories=102},
		{str="≈ Фруктовый салат (100г)",	calories=103},
		{str="≈ Филе индейки (100г)",	calories=104},
		{str="≈ Свинной балык (100г)",	calories=105},
		{str="≈ Плов с курицей (100г)",	calories=106},
		{str="≈ Рис (100г)",	calories=113},
		{str="≈ Цеппелины (100г)",	calories=117},
		{str="≈ Яичница",	calories=119},
		{str="≈ Икра кабачковая (100г)",	calories=122},
		{str="≈ Майонез японский (100г)",	calories=134},
		{str="≈ Зефир (1шт)",	calories=135},
		{str="≈ Творог (100г)",	calories=136},
		{str="≈ Авокадо ролл",	calories=140},
		{str="≈ Капучино (100г)",	calories=140},
		{str="≈ Лобио (100г)",	calories=141},
		{str="≈ Говядина, язык (100г)",	calories=146},
		{str="≈ Говяжий гуляш (100г)",	calories=148},
		{str="≈ Куриное филе вар. (100г)",	calories=153},
		{str="≈ Картошка жар. (100г)",	calories=154},
		{str="≈ Пицца маргарита (100г)",	calories=157},
		{str="≈ Тефтели (100г)",	calories=159},
		{str="≈ Гречневая каша (100г)",	calories=160},
		{str="≈ Сырок Чудо (40г)",	calories=164},
		{str="≈ Хлеб ржаной (100г)",	calories=165},
		{str="≈ Индейка жареная (100г)",	calories=165},
		{str="≈ Салат мимоза (100г)",	calories=183},
		{str="≈ Долма (100г)",	calories=183},
		{str="≈ Копченая курица (100г)",	calories=184},
		{str="≈ Салат Оливье (100г)",	calories=187},
		{str="≈ Зразы картофельные (100г)",	calories=190},
		{str="≈ Биток свиной (100г)",	calories=195},
		{str="≈ Сардельки (100г)",	calories=198},
		{str="≈ Лосось (201г)",	calories=201},
		{str="≈ Сметана 20% (100г)",	calories=204},
		{str="≈ Сливки (100г)",	calories=206},
		{str="≈ Паста болонез (100г)",	calories=208},
		{str="≈ Азу (100г)",	calories=214},
		{str="≈ Хлеб черный (100г)",	calories=214},
		{str="≈ Цукаты (100г)",	calories=216},
		{str="≈ Салат столичный (100г)",	calories=217},
		{str="≈ Сельдь соленая (100г)",	calories=217},
		{str="≈ Жульен грибной (100г)",	calories=219},
		{str="≈ Салат цезарь (100г)",	calories=221},
		{str="≈ Омлет (100г)",	calories=222},
		{str="≈ Светлое пиво (0,5л)",	calories=225},
		{str="≈ Хлеб овсяный (100г)",	calories=226},
		{str="≈ Рагу из баранины (100г)",	calories=226},
		{str="≈ Пломбир (100г)",	calories=227},
		{str="≈ Гамбургер",	calories=229},
		{str="≈ Жаркое из свинины (100г)",	calories=233},
		{str="≈ Батон (100г)",	calories=235},
		{str="≈ Лаваш (100г)",	calories=236},
		{str="≈ Водка 40% (100г)",	calories=237},
		{str="≈ Бастурма (100г)",	calories=240},
		{str="≈ Хамон (100г)",	calories=241},
		{str="≈ Хлеб пшеничный (100г)",	calories=242},
		{str="≈ Сосиски русские (100г)",	calories=243},
		{str="≈ Равиоли (100г)",	calories=245},
		{str="≈ Красная икра (100г)",	calories=249},
		{str="≈ Шаурма (100г)",	calories=250},
		{str="≈ Колбаса вареная (100г)",	calories=257},
		{str="≈ Сосиски куриные (100г)",	calories=259},
		{str="≈ Котлеты (100г)",	calories=260},
		{str="≈ Изюм (100г)",	calories=262},
		{str="≈ Чизбургер",	calories=264},
		{str="≈ Сосиски мол. (100г)",	calories=270},
		{str="≈ Ветчина (100г)",	calories=270},
		{str="≈ Мойва копченая (100г)",	calories=270},
		{str="≈ МакНаггетс (100г)",	calories=272},
		{str="≈ Кровянка (100г)",	calories=274},
		{str="≈ Мясо в шубе (100г)",	calories=274},
		{str="≈ Пельмени (100г)",	calories=275},
		{str="≈ Плов со свининой (100г)",	calories=281},
		{str="≈ Лосось гриль (100г)",	calories=283},
		{str="≈ Сырок Дружба (100г)",	calories=287},
		{str="≈ Черная икра (100г)",	calories=289},
		{str="≈ Майонез (100г)",	calories=299},
		{str="≈ Цветочный мед (100г)",	calories=302},
		{str="≈ Картофель фри (100г)",	calories=303},
		{str="≈ Салат Оливье (100г)",	calories=305},
		{str="≈ Скумбрия соленая (100г)",	calories=305},
		{str="≈ Финики (100г)",	calories=306},
		{str="≈ Оладьи с яблоками (100г)",	calories=306},
		{str="≈ Голубцы (100г)",	calories=311},
		{str="≈ Беляш (100г)",	calories=320},
		{str="≈ Оладьи (100г)",	calories=322},
		{str="≈ Омлет с сыром (100г)",	calories=324},
		{str="≈ Колбаса ливерная (100г)",	calories=326},
		{str="≈ Колбаски охотничьи (100г)",	calories=326},
		{str="≈ Пончики (100г)",	calories=329},
		{str="≈ Ватрушка (100г)",	calories=331},
		{str="≈ Блины с маслом (100г)",	calories=332},
		{str="≈ Люля-кебаб (100г)",	calories=339},
		{str="≈ Сушки (100г)",	calories=341},
		{str="≈ Макароны Макфа (100г)",	calories=344},
		{str="≈ Спагетти (100г)",	calories=344},
		{str="≈ Кекс (100г)",	calories=345},
		{str="≈ Пряник (100г)",	calories=350},
		{str="≈ Бефстроганов (100г)",	calories=355},
		{str="≈ Российский сыр (100г)",	calories=360},
		{str="≈ Кукурузные хлопья (100г)",	calories=363},
		{str="≈ Макароны (100г)",	calories=371},
		{str="≈ Бифштекс (100г)",	calories=384},
		{str="≈ Сухари (100г)",	calories=386},
		{str="≈ Сахар-песок  (100г)",	calories=398},
		{str="≈ Козинаки (100г)",	calories=419},
		{str="≈ Овсяное печенье (100г)",	calories=440},
		{str="≈ Лапша Роллтон  (100г)",	calories=448},
		{str="≈ Торт муравейник (100г)",	calories=452},
		{str="≈ Шницель (100г)",	calories=456},
		{str="≈ Лазанья (100г)",	calories=460},
		{str="≈ Фуа-гра (100г)",	calories=462},
		{str="≈ Торт Медовик  (100г)",	calories=478},
		{str="≈ Попкорн (100г)",	calories=480},
		{str="≈ Твикс",	calories=483},
		{str="≈ Сникерс",	calories=497},
		{str="≈ Бекон (100г)",	calories=500},
		{str="≈ Биг Мак",	calories=510},
		{str="≈ Чипсы Lays Max (100г)",	calories=510},
		{str="≈ Халва (100г)",	calories=522},
		{str="≈ Шоколад KitKat",	calories=524},
		{str="≈ Роял Чизбургер (100г)",	calories=530},
		{str="≈ Тирамису (100г)",	calories=540},
		{str="≈ Чипсы Pringles (100г)",	calories=540},
		{str="≈ Шоколад (100г)",	calories=546},
		{str="≈ Торт Наполеон (100г)",	calories=552},
		{str="≈ Салями (100г)",	calories=568},
		{str="≈ Гусь жареный (100г)",	calories=620},
		{str="≈ Майонез Евр. (100г)",	calories=665},
		{str="≈ Пельмени жареные (100г)",	calories=764},
		{str="≈ Сало (100г)",	calories=797},
		{str="≈ Биг Тейсти",	calories=850},
    },

    ok='ОК',

    hour='ч.',
    minute='мин.',
    month='мес.',
    day='дней',
    step="шагов",
    km='км',
    minute_format='%d мин.',
    hour_minute_format='%d ч. %d мин.',
    hour_format='%d ч.',

    welcome_use='Добро пожаловать',
    last_week_walked_format='%d шагов пройдено на прошлой неделе.',
    last_week_walked_info_format='Пройдено %d км, сожжено %d ккал.',
    last_month_walked_format='%d шагов пройдено в прошлом месяце.',
    last_month_walked_info_format='Пройдено %d км, сожжено %d ккал.',

    get_over_format=", приблизительно %d грамм жира.",
    click_to_get_help="Узнайте, что вы можете делать с Mi Band.",
    take_a_walk="Пройдитесь с Mi Band.",
    take_a_walk_info="Mi Band будет отслеживать вашу активность и поможет быть здоровым.",
    unlock_hint="Разблокируйте телефон с помощью Mi Band",
    unlock_hint_info="Попрощайтесь с дневной рутиной.",
	no_data_hint_0="Национальный Фонд Сна США рекомендует спать на протяжении 7~9 часов.",
    no_data_hint_1="Повторение - мать учения.",
    no_data_hint_2="Стремитесь к прогрессу а не идеалу.",
    no_data_hint_3="Не важно на сколько медленно вы идете. Вы все еще оставляете других позади, на диване.",
    not_binded_hint="Mi Band не подключен к этому аккаунту, пожалуйста подключите браслет.",
    new_record_info="Вы только что побили рекорд в ходьбе!",
    new_record_format="%d шагов, %s %d",
    today_goal_reached="Поздравляю! Вы достигли заданной цели сегодня.",
    week_continue_reach_goal="Вы достигали заданной цели каждый день на протяжении всей недели! Какая чудесная неделя!",

    -- Continue reach goals string
    challenge_format="Вы достигали заданной цели на протяжении %d дней!",
    personal_best_format="Ваша лучшая продолжительность рекордов - %d дней!",
    continue_with_skips_title="Вы не достигли цели вчера, назовем это Днем Отдыха ;)",
    continue_with_skips_title_today="Вы сегодня не достигли цели, назовем это Днем Отдыха ;)",
    personal_best_with_skips_format="Вы только что сделали лучший рекорд за %d дней! У вас осталось %d Дней Отдыха ;)",
    continue_used_n_skips_format="Вы достигали цели на протяжении %d дней! У вас все еще есть %d Дней Отдыха ;)",
    continue_used_0_skips_format="Вы достигали цели на протяжении %d дней! У вас не осталось Дней Отдыха.",
    personal_best_on_skip_day_title="Вы достигали цели на протяжении %d дней! В награду вы получаете один День Отдыха ;) Вы можете воспользоваться им в день, когда вы не достигли цели.",
    personal_best_on_skip_day_info="Вы получите один День Отдыха за достижения цели каждые 7 дней подряд. Мы автоматически используем его если вы не достигните вашей цели. Один День Отдыха приравнивается одному дню.",
    manual_lazy_title="Вы не достигли сегодня своей цели, назовем это Днем Отдыха?",
    manual_lazy_subtitle="Этот день будет вам прощен если вы согласитесь.",
    manual_lazy_title_used="Продолжительность достижения цели сохранена. Наслаждайтесь!",
    manual_lazy_subtitle_used="Продолжительность достижения будет засчитана позже.",
    manual_fail_ytd_title = "К сожалению, продолжительность достижений прервана вчера.",
    manual_fail_ytd_subtitle = "Продолжительность достижений до вчера - %d.",

    active_time_format_0="%d м.",
    active_time_format_1="%d ч.",
    active_time_format_2="%d ч. %d мин.",
    activie_run_format_0="Пробежали %s. Отличная работа!",
    activie_run_format_1="Пробежали %s. Супер результат!",
    activie_run_format_2="Пробежали %s, Нереальная выносливость, вы молодец!",
    activie_run_consumed="Сожжено %d ккал %s",

    get_distance_format=" всего %d м.",
    activity_walk_format="%s Пройдено %d шагов, %s",
    activity_walk_consumed_format="Сожжено %d ккал %s", 
    activity_rope_skipping_format="%s Прыгали на скакалке %d раз.",
    activity_situp_format="%s Сделали упражнение для пресса %d раз.",
    activity_consumed_format="Сожжено %d ккал %s",
    activity_activity_format="%s %s тренировки, %s",
    activity_activity_format_run="%s %s тренировки, пробежали %s",
    last_night_sleeped_good_format="Прошлой ночью вы спали %s \nКакой чудесный сон!",
    last_night_sleeped_normal_format="Прошлой ночью вы спали %s",
    deep_sleep_format="В стадии глубокого сна вы находились %s",

    battery_low_info="Низкий заряд, зарядите Mi Band.",
    battery_very_low_info="Подключите к зарядному устройству",

    cannot_find_bracelet="Не удалось найти ваш Mi Band?",
    cannot_find_bracelet_info="Убедитесь в том, что Mi Band находится близко к телефону.",
    challenge_to_get="%s дней с момента нового рекорда!",
    record_reach_max="Вы побили свой рекорд!",
    new_record_born="Новый рекорд!",

    ---====== Weather tips ===============
    weather_tips_title_0 = "Сильное загрязнение. Постарайтесь остаться дома.",
    weather_tips_title_1 = "Сильное загрязнение. Постарайтесь остаться дома.",
    weather_tips_info = "Дома вы сможете заняться упражнениями для пресса и прыжками со скакалкой!",
}
localization_Italian_table = {
     calories_table={
        {str="Equivalente a 2 uova sode",	calories=96},
        {str="Equivalente a 1 fetta di pane",	calories=100},
        {str="Equivalente a 1 bottiglia di tè freddo",	calories=112},
        {str="Equivalente a 1 omelette",	calories=118},
        {str="Equivalente a 2 fette di arrosto",	calories=124},
        {str="Equivalente a 1 bibita gassata",	calories=153},
        {str="Equivalente a 3 fette di arrosto",	calories=186},
        {str="Equivalente a 2 uova sode",	calories=192},
        {str="Equivalente a 2 fette di pane",	calories=200},
        {str="Equivalente a 1 porzione di riso",	calories=210},
        {str="Equivalente a 1 panino",	calories=221},
        {str="Equivalente a 1 barbabietola",	calories=223},
        {str="Equivalente a 2 bottiglie di tè freddo",	calories=224},
        {str="Equivalente a 1 sacchetto piccolo di patatine",	calories=224},
        {str="Equivalente a 1 fetta di torta",	calories=224},
        {str="Equivalente a 2 omelette",	calories=236},
        {str="Equivalente a 4 fette di arrosto",	calories=248},
        {str="Equivalente a 1 hamburger",	calories=260},
        {str="Equivalente a 1 frittella",	calories=270},
        {str="Equivalente a 1 panino con carne",	calories=272},
        {str="Equivalente a 3 uova sode",	calories=288},
        {str="Equivalente a 1 gelato",	calories=290},
        {str="Equivalente a 3 fette di pane",	calories=300},
        {str="Equivalente a 2 bibite gassate",	calories=306},
        {str="Equivalente a 1 sacchetto di patatine",	calories=328},
        {str="Equivalente a 3 omelette",	calories=354},
        {str="Equivalente a 1 frittata",	calories=375},
        {str="Equivalente a 4 fette di pane",	calories=400},
        {str="Equivalente a 1 sacchetto grande di patatine",	calories=402},
        {str="Equivalente a 2 porzioni di riso",	calories=420},
        {str="Equivalente a 2 panini",	calories=442},
        {str="Equivalente a 2 barbabietole",	calories=446},
        {str="Equivalente a 1 torta",	calories=448},
        {str="Equivalente a 1 porzione di noodles",	calories=470},
        {str="Equivalente a 5 fette di pane",	calories=500},
        {str="Equivalente a 1 piatto di riso fritto",	calories=516},
        {str="Equivalente a 2 hamburger",	calories=520},
        {str="Equivalente a 2 frittelle",	calories=540},
        {str="Equivalente a 2 panini di carne",	calories=544},
        {str="Equivalente a 2 gelati",	calories=580},
        {str="Equivalente a 1 piatto di pasta",	calories=581},
        {str="Equivalente a 1 piatto di pasta al ragù",	calories=593},
        {str="Equivalente a 10 fette di arrosto",	calories=620},
        {str="Equivalente a 3 porzioni di riso",	calories=630},
        {str="Equivalente a 3 panini",	calories=663},
        {str="Equivalente a 2 frittate",	calories=750},
        {str="Equivalente a 3 frittate",	calories=810},
        {str="Equivalente a3 panini con carne",	calories=816},
    },

    ok='OK',

    hour='ore',
    minute='min',
    month='mese',
    day='giorno',
    step="passo",
    km='KM',
    minute_format='%d min',
    hour_minute_format='%d ore %d min',
    hour_format='%d ore',

    welcome_use="Ciao, io sono MiBand",
    last_week_walked_format='Settimana scorsa hai fatto %d passi',
    last_week_walked_info_format='Hai camminato per %d km, consumando %d Kcal',
    last_month_walked_format='Nell\'ultimo mese hai fatto %d passi',
    last_month_walked_info_format='Hai camminato per %d km, consumando %d Kcal',

    get_over_format=", quasi %d grammi di grasso",
    click_to_get_help="Scopri cosa puoi fare con MiBand",
    take_a_walk="Fatti un giro con MiBand",
    take_a_walk_info="MiBand traccerà le tue attività e ti aiuterà a stare più in forma",
    unlock_hint="Sblocca il telefono con MiBand",
    unlock_hint_info="Saluta i vecchi tempi",
    no_data_hint_0="Continua a muoverti, fai che l\'esercizio sia parte della tua vita",
    no_data_hint_1="Vuoi essere felice? Corri!",
    no_data_hint_2="Un\'esercizio cardio ti manterrà fresco e leggero tutti i giorni!",
    no_data_hint_3="Il sonno di un adulto è profondo per il 15%-20% del totale",
    not_binded_hint="Non hai collegato alcun MiBand al tuo account, fallo ora!",
    new_record_info="Wow! Hai appena raggiunto un nuovo record camminando!",
    new_record_format="Nuovo Record, %d passi, %s %d",
    today_goal_reached="Congratulazioni! Hai raggiunto il tuo obiettivo giornaliero",
    week_continue_reach_goal="You have achieved your goal every day for an entire week! What an awesome week!",
    challenge_format="Hai raggiunto i tuoi obiettivi %d giorni di fila!",
    personal_best_format="Il tuo record più grande è di %d giorni consecutivi!",
    active_time_format_0="%d min",
    active_time_format_1="%d ore",
    active_time_format_2="%d ore %d min",
    activie_run_format_0="Hai corso %s. Bel Lavoro!",
    activie_run_format_1="Hai corso %s. Fantastico!",
    activie_run_format_2="Hai corso %s, una resistenza incredibile!",
    activie_run_consumed="Hai bruciato %d Kcal. %s",

    get_distance_format=", per un totale di %d m",
    activity_walk_format="%s Hai fatto %d passi in cammino %s",
    activity_walk_consumed_format="Bruciate %d Kcal %s",

    activity_activity_format="Durata Esercizio: %s %s %s",
    last_night_sleeped_good_format="Questa notte hai dormito per %s. Che dormita!",
    last_night_sleeped_normal_format="Questa notte hai dormito per %s.",
    deep_sleep_format="Il sonno profondo è durato %s.",

    battery_low_info="La batteria è in esaurimento, ricaricala",
    battery_very_low_info="Collega l\'alimentazione",

    cannot_find_bracelet="Non riesci a trovare MiBand?",
    cannot_find_bracelet_info="Controlla che la batteria sia sufficientemente carica e avvicinalo al telefono",

    challenge_to_get="Mancano %s giorni al nuovo record!",
    record_reach_max="Hai migliorato il tuo record!",
    new_record_born="Nuovo record!",

    --=================== Game =====================
	game_register = "National mila passi al giorno in sette giorni, vincendo il miglio telefono 4", 
	game_not_register_info = "Condividi microblogging Weibo premiato",
     game_register_info = "è avvenuta registrazione, giorni il conto alla rovescia% s",
     game_playing = "Giornata Nazionale di sette giorni diecimila passi al giorno nei primi giorni della sfida% s",
     game_playing_done = "Giornata Nazionale di sette giorni diecimila passi al giorno nel primo% s giorni per raggiungere",
     game_playing_lastday = "ultimo giorno del Day Challenge è in fase di completamento mille passi di fila, il rifornimento di carburante,",
     game_playing_lastday_done = "Congratulazioni, Festa Nazionale sette giorni diecimila passi al giorno in una sfida di successo,",
     game_playing_bonus_info = "tenente risultati saranno annunciati a gennaio% s% s Day",
     click_to_show_result = "Clicca per visualizzare lo stato di avanzamento delle attività,",
     game_fail_title_ytd = "Purtroppo, ieri non ha raggiunto 10.000 passi",
     game_fail_title = "Purtroppo,% s% s mesi non ha raggiunto 10.000 passi al giorno,",
     game_failed_title = "National mila passi al giorno in sette giorni",
     game_fail_info = "continuare a concentrarsi sulle attività, la condivisione di microblogging Weibo premiato",

     game_bonus_hit = "Congratulazioni, si diventa una Giornata Nazionale sette giorni diecimila passi al giorno a vincitori",
     game_bonus_hit_info = "Clicca per visualizzare i risultati vincenti,",
     game_bonus_miss = "National mila passi al giorno in sette giorni, vincendo i risultati sono stati annunciati,",
     game_bonus_miss_info = "Vai a vedere che ha vinto la lotteria,",
     game_bonus_open = "% s risultati vincitori saranno annunciati maggio% s Day, quindi rimanete sintonizzati,",
     game_bonus_open_tomorrow = "vincenti risultati saranno annunciati domani, quindi rimanete sintonizzati,",
     game_bonus_open_today = "vincenti risultati saranno resi noti oggi, quindi rimanete sintonizzati,",

     share_to_content_for_event = " Giornata Nazionale sette giorni la linea telefonica miglio era quattromila passi applicazione a caldo della campagna, non c\'è braccialetto? inoltrato questa occasione microblogging di vincere braccialetti codice F cliccare sul link per visualizzare i dettagli dell\'evento.",
     game_share_to_registered = "mi sono iscritto alla linea telefonica miglio giapponese era quattromila gradini attività, si è disposti a stare in silenzio benedizione ho ancora venuto qui per frequentarla? dalle attività iniziarono solo% s giorni, vieni firmarlo,",
     game_share_to_finished = "10.000 passi obiettivo oggi il completamento",
     game_share_to_not_finished = "verso 10.000 passi avanti",
     game_share_to_failed = "non mi aspettavo, in realtà ho fallito la sfida",
     game_share_to_success = "Sfida Successo! camminato un totale di step% s",
     game_share_to_hit_bonus = "un vincente distratto, Vieni spettatori darmi lode,",
     game_share_to_not_hit_bonus = "no disegnato quando il premio successivo è quello di salvare il carattere di",
     less_than_one = "meno di un",
}
